/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * UIAgendar.java
 *
 * Created on 27-nov-2008, 20:59:41
 */

package ui;

import java.awt.event.ActionListener;
import java.awt.event.FocusListener;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import talitakumi.framework.DataParameter;
import talitakumi.model.core.Clientes;

/**
 *
 * @author rupertus
 */
public class UIAgendar extends javax.swing.JFrame {

    /** Creates new form UIAgendar */
    public UIAgendar() {
        initComponents();

        //cedula.setText("0000000");
        documento.setSelectionStart(0);
        documento.setSelectionEnd(15);
        this.setFormatoCedulaUruguaya();
        Date hoy = new java.util.Date();
        fechaHoy2.setFormats("dd/MM/yyyy");
        fechaHoy2.setDate(hoy);

    }


    public int getCedula() {

        int doc = -1;
        doc = Integer.parseInt(documento.getText());
        return(doc);
    }


    public void setPaciente(DataParameter p)  {

        apellidos.setText((String) p.get("apellidos"));
        nombres.setText((String) p.get("nombres"));
       
  
        DateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy");
        Date d = (Date) p.get("fechanacimiento");

        String s = dateFormat.format(d);

        
        Character sex =  (Character) p.get("sexo");
        if(sex=='M')
            masculino.setSelected(true);
        else
            femenino.setSelected(true);
    }

 
    public void setFormatoCedulaUruguaya() {
        try {
            String anterior = documento.getText();
            documento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("########")));
            documento.setText(anterior);
        } catch (ParseException ex) {
            Logger.getLogger(UIAgendar.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void setFormatoCedulaLibre() {

        try {
            documento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("***********************")));
            documento.setText("0");
        } catch (ParseException ex) {
            Logger.getLogger(UIAgendar.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    
    public String getApellidos() {

        return(apellidos.getText());
    }

    public String getNombres() {
        return(nombres.getText());
    }

    public void setNombres(String nombres){
       this.nombres.setText(nombres);
    }

    public void setApellidos(String apellidos){
        this.apellidos.setText(apellidos);
    }

    public char getSexo() {

        char s;

        if(masculino.isSelected())
            s = 'M';
        else
            s = 'F';

        return(s);
    }

   
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sexo = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        apellidos = new com.kcreativa.pitosycornetas.KTextBox();
        jLabel3 = new javax.swing.JLabel();
        nombres = new com.kcreativa.pitosycornetas.KTextBox();
        jLabel9 = new javax.swing.JLabel();
        masculino = new javax.swing.JRadioButton();
        femenino = new javax.swing.JRadioButton();
        documento = new com.kcreativa.pitosycornetas.KFormattedTextBox();
        labelfechanacimiento1 = new javax.swing.JLabel();
        hora = new com.kcreativa.pitosycornetas.KFormattedTextBox();
        labelfechanacimiento2 = new javax.swing.JLabel();
        tipoestudio = new javax.swing.JComboBox();
        labelfechanacimiento3 = new javax.swing.JLabel();
        cancelar = new javax.swing.JButton();
        guardar = new javax.swing.JButton();
        fechaHoy2 = new org.jdesktop.swingx.JXDatePicker();
        jLabel4 = new javax.swing.JLabel();
        telefono = new com.kcreativa.pitosycornetas.KTextBox();
        clientes = new javax.swing.JComboBox();
        labelfechanacimiento4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        observaciones = new javax.swing.JTextArea();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(null);

        jLabel1.setText("DOCUMENTO");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 10, 100, 16);

        jLabel2.setText("APELLIDOS");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(250, 10, 190, 16);

        apellidos.setBackground(new java.awt.Color(246, 246, 246));
        apellidos.setEditando(true);
        apellidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apellidosActionPerformed(evt);
            }
        });
        getContentPane().add(apellidos);
        apellidos.setBounds(330, 10, 187, 20);

        jLabel3.setText("CELULAR");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(540, 40, 70, 16);

        nombres.setBackground(new java.awt.Color(246, 246, 246));
        nombres.setEditando(true);
        getContentPane().add(nombres);
        nombres.setBounds(620, 10, 190, 20);

        jLabel9.setText("SEXO");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(10, 40, 100, 16);

        sexo.add(masculino);
        masculino.setText("MASCULINO");
        getContentPane().add(masculino);
        masculino.setBounds(80, 40, 140, 23);

        sexo.add(femenino);
        femenino.setSelected(true);
        femenino.setText("FEMENINO");
        femenino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femeninoActionPerformed(evt);
            }
        });
        getContentPane().add(femenino);
        femenino.setBounds(240, 40, 210, 23);

        documento.setBackground(new java.awt.Color(246, 246, 246));
        documento.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        documento.setMinimumSize(new java.awt.Dimension(0, 23));
        documento.setPreferredSize(new java.awt.Dimension(0, 23));
        getContentPane().add(documento);
        documento.setBounds(110, 10, 123, 20);

        labelfechanacimiento1.setText("SERVICIO");
        getContentPane().add(labelfechanacimiento1);
        labelfechanacimiento1.setBounds(10, 90, 70, 16);

        hora.setBackground(new java.awt.Color(246, 246, 246));
        hora.setEditando(true);
        try {
            hora.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(hora);
        hora.setBounds(630, 90, 120, 19);

        labelfechanacimiento2.setText("FECHA :");
        getContentPane().add(labelfechanacimiento2);
        labelfechanacimiento2.setBounds(390, 90, 110, 16);

        getContentPane().add(tipoestudio);
        tipoestudio.setBounds(80, 90, 300, 27);

        labelfechanacimiento3.setText("HORA :");
        getContentPane().add(labelfechanacimiento3);
        labelfechanacimiento3.setBounds(580, 90, 120, 16);

        cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/remove.png"))); // NOI18N
        cancelar.setText("Cancelar");
        getContentPane().add(cancelar);
        cancelar.setBounds(630, 170, 120, 28);

        guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ok24.png"))); // NOI18N
        guardar.setText("Guardar");
        getContentPane().add(guardar);
        guardar.setBounds(630, 130, 120, 30);

        fechaHoy2.setFormats("dd/mm/aaaa");
        getContentPane().add(fechaHoy2);
        fechaHoy2.setBounds(450, 90, 120, 28);

        jLabel4.setText("NOMBRES");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(540, 10, 70, 16);

        telefono.setBackground(new java.awt.Color(246, 246, 246));
        telefono.setEditando(true);
        getContentPane().add(telefono);
        telefono.setBounds(620, 40, 190, 20);

        getContentPane().add(clientes);
        clientes.setBounds(80, 60, 300, 27);

        labelfechanacimiento4.setText("CLIENTE");
        getContentPane().add(labelfechanacimiento4);
        labelfechanacimiento4.setBounds(10, 60, 70, 16);

        jLabel5.setText("Observaciones");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 130, 100, 16);

        observaciones.setColumns(20);
        observaciones.setRows(5);
        jScrollPane1.setViewportView(observaciones);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(120, 130, 450, 90);
    }// </editor-fold>//GEN-END:initComponents

    private void femeninoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femeninoActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_femeninoActionPerformed

    private void apellidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apellidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_apellidosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.kcreativa.pitosycornetas.KTextBox apellidos;
    private javax.swing.JButton cancelar;
    private javax.swing.JComboBox clientes;
    private com.kcreativa.pitosycornetas.KFormattedTextBox documento;
    private org.jdesktop.swingx.JXDatePicker fechaHoy2;
    private javax.swing.JRadioButton femenino;
    private javax.swing.JButton guardar;
    private com.kcreativa.pitosycornetas.KFormattedTextBox hora;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelfechanacimiento1;
    private javax.swing.JLabel labelfechanacimiento2;
    private javax.swing.JLabel labelfechanacimiento3;
    private javax.swing.JLabel labelfechanacimiento4;
    private javax.swing.JRadioButton masculino;
    private com.kcreativa.pitosycornetas.KTextBox nombres;
    private javax.swing.JTextArea observaciones;
    private javax.swing.ButtonGroup sexo;
    private com.kcreativa.pitosycornetas.KTextBox telefono;
    private javax.swing.JComboBox tipoestudio;
    // End of variables declaration//GEN-END:variables

    
    public void setDocumento(int undocumento) {
        this.documento.setText(undocumento+"");
    }

     public void setCancelarListener(ActionListener al) {

        this.cancelar.addActionListener(al);
    }

     public void setAlmacenarListener(ActionListener al) {

        this.guardar.addActionListener(al);
    }

    public void doMaximize() {
        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-1024)/2, (screenSize.height-768)/2, 1024, 768);
    }

    public Date getFecha() {
        return(fechaHoy2.getDate());
    }

    public String getHora() {
        
        return(hora.getText());
    }

    public int getPaciente() {
        
        int ced = Integer.parseInt(documento.getText());
        return(ced);
    }

    public int getActividad() {
        
        return(tipoestudio.getSelectedIndex());
    }

    public void addActividad(String descripcion) {
        
        tipoestudio.addItem(descripcion);
    }

    public String getTelefono() {
        return(telefono.getText());
    }

    public void setFecha(Date fecha) {
        fechaHoy2.setDate(fecha);
    }

    public void setHora(String hora) {
        this.hora.setText(hora);
    }

    public void setTelefono(String movil) {
        telefono.setText(movil);
    }

    public String getObservaciones() {

        return(observaciones.getText());
    }

    public void setSexo(char sexo) {

        if(sexo=='F')
            femenino.setSelected(true);
        else
            masculino.setSelected(true);
    }

    public void setCargarPacienteListener(FocusListener fl) {

            documento.addFocusListener(fl);
    }

    public void setListaProcedencias(List<Clientes> lp) {


        DefaultComboBoxModel dcbm = new DefaultComboBoxModel();

        for(Clientes p : lp) {

            dcbm.addElement(p.getNombre());
        }

        clientes.setModel(dcbm);
    }

    public int getProcedenciaElegida() {
        return(clientes.getSelectedIndex());
    }
       
}
