/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * UIRecepcion.java
 *
 * Created on 20-nov-2008, 8:18:45
 */

package ui;

import java.awt.event.MouseListener;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import ctrl.TelefonistaCtrl.RecargarListener;
import ctrl.TelefonistaCtrl.SalirListener;
import java.awt.Color;
import java.awt.event.ActionListener;
import java.beans.PropertyChangeListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import javax.swing.JCheckBox;

/**
 *
 * @author rupertus
 */
public class UITelefonista extends javax.swing.JFrame {

    HashMap <Integer, JCheckBox> consultorios;
    ActionListener consultoriosListener;
    Integer consultorioelegido;
    /** Creates new form UIRecepcion */
    public UITelefonista() {
        initComponents();

        jSplitPane1.setDividerLocation(500);

        consultorios = new HashMap();
        consultorioelegido = 0;
        tableIcon1.setRowHeight(32);
        tableIcon1.setAutoCreateRowSorter(true);

        cuaderno.setStatusBarVisible(false);
        cuaderno.setSourceEditorVisible(false);
        cuaderno.setPreviewVisible(false);
        cuaderno.wrapNewLineIntoBR(true);

        cuaderno.setRemovedMenuItems("openLocationMenuItem, closeFileMenuItem, newFileMenuItem, saveasFileMenuItem");
        cuaderno.setRemovedToolbarItems("newFileButton, openFileButton, insertImageButton, saveFileButton");
    }

    public void cambiarEstadoConsultorio(Integer consultorio, boolean activo) {

        JCheckBox jcb = consultorios.get(consultorio);
        jcb.setSelected(activo);

    }

    public void crearPacientesListener(ActionListener pacientesListener) {
        
        pacientes.addActionListener(pacientesListener);
    }

    public void crearAgendarListener(ActionListener AgendarListener) {

        agendar.addActionListener(AgendarListener);
    }

    public Integer getConsultorioElegido() {

        return(consultorioelegido);
    }

    public int getColumnaTablaPacientes() {

        int z = this.tableIcon1.getSelectedColumn();
        
        return(z);
    }
    public int getIndiceTablaPacientes() {

        return(this.tableIcon1.getSelectedRow());
    }

    public void doMaximize() {
        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-1024)/2, (screenSize.height-768)/2, 1024, 768);
    }
    
    public void recargarListener(RecargarListener recargarListener) {
        recargar.addActionListener(recargarListener);
    }

    public void salirListener(SalirListener salirListener) {
        salir.addActionListener(salirListener);
    }

    public void setFuncionario(String usuario) {
        funcionario.setText(usuario);
    }

    public void setHora(String hora) {
        this.hora.setText(hora);
    }

    public void setModelListaAgenda(DefaultTableModel dftm) {

        tableIcon1.setModel(dftm);
        tableIcon1.repaint();
        tableIcon1.validate();
    }

    public void setAnchoColumna(int i, int ancho) {

        tableIcon1.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        TableColumn col = tableIcon1.getColumnModel().getColumn(i);
        col.setPreferredWidth(ancho);
    }

    public void pintarFilaAgenda(int fila, Color color) {


    }

    public void setPacientesListener(MouseListener pacienteElegidoListener) {

        this.tableIcon1.addMouseListener(pacienteElegidoListener);
    }

    public void crearCalendarioListener(MouseListener fechaListener) {

        jCalendar1.getDayChooser().setAlwaysFireDayProperty(true);
        jCalendar1.getDayChooser().addMouseListener(fechaListener);
        jCalendar1.getMonthChooser().addMouseListener(fechaListener);
        jCalendar1.getYearChooser().addMouseListener(fechaListener);

    }

  

    public void crearBuscarListener(ActionListener buscarListener) {

        this.tareas.addActionListener(buscarListener);
    }

    public Object getValorEnXY(int col, int fila) {

        return(this.tableIcon1.getValueAt(col, fila));
    }

//    public void crearHigieneListener(ActionListener higieneListener) {
//
//        higiene.addActionListener(higieneListener);
//
//    }



    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        funcionario = new javax.swing.JLabel();
        hora = new javax.swing.JLabel();
        jToolBar2 = new javax.swing.JToolBar();
        fechaHoy = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        agendar = new javax.swing.JButton();
        tareas = new javax.swing.JButton();
        pacientes = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        recargar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        resumen = new javax.swing.JEditorPane();
        jPanel3 = new javax.swing.JPanel();
        salir = new javax.swing.JButton();
        jSplitPane1 = new javax.swing.JSplitPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableIcon1 = new com.kcreativa.pitosycornetas.TableIcon();
        jPanel5 = new javax.swing.JPanel();
        jCalendar1 = new com.toedter.calendar.JCalendar();
        cuaderno = new sferyx.administration.editors.HTMLEditor();
        save = new javax.swing.JButton();

        setTitle("Recepcion");
        setUndecorated(true);

        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.LINE_AXIS));
        getContentPane().add(jPanel4, java.awt.BorderLayout.LINE_END);

        jPanel2.setMaximumSize(new java.awt.Dimension(32767, 64));
        jPanel2.setOpaque(false);
        jPanel2.setPreferredSize(new java.awt.Dimension(545, 32));

        jLabel4.setText("Funcionario");

        funcionario.setFont(new java.awt.Font("Lucida Grande", 1, 13));
        funcionario.setText("jLabel5");

        hora.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        hora.setText("hh:mm");

        jToolBar2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jToolBar2.setFloatable(false);
        jToolBar2.setRollover(true);

        fechaHoy.setFont(new java.awt.Font("Lucida Grande", 1, 14));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(funcionario, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(118, 118, 118)
                .addComponent(fechaHoy, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 219, Short.MAX_VALUE)
                .addComponent(hora, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jToolBar2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1046, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(funcionario)
                        .addComponent(fechaHoy, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(hora, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        agendar.setFont(new java.awt.Font("Lucida Grande", 0, 8)); // NOI18N
        agendar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/today.png"))); // NOI18N
        agendar.setText("Agendar");
        agendar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        agendar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        agendar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                agendarMouseClicked(evt);
            }
        });
        jToolBar1.add(agendar);

        tareas.setFont(new java.awt.Font("Lucida Grande", 0, 8)); // NOI18N
        tareas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/buscarmini.png"))); // NOI18N
        tareas.setText("Buscar");
        tareas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tareas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(tareas);

        pacientes.setFont(new java.awt.Font("DejaVu Sans", 0, 8)); // NOI18N
        pacientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/personal.png"))); // NOI18N
        pacientes.setText("Pacientes");
        pacientes.setPreferredSize(new java.awt.Dimension(85, 40));
        jToolBar1.add(pacientes);
        jToolBar1.add(jSeparator1);

        recargar.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        recargar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/reload_page.png"))); // NOI18N
        recargar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(recargar);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(null);

        resumen.setBackground(new java.awt.Color(153, 153, 153));
        resumen.setContentType("text/html");
        resumen.setEditable(false);
        resumen.setDragEnabled(false);
        jScrollPane2.setViewportView(resumen);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(0, 0, 700, 70);

        jToolBar1.add(jPanel1);

        jPanel3.setMaximumSize(new java.awt.Dimension(100, 100));
        jPanel3.setMinimumSize(new java.awt.Dimension(50, 84));
        jPanel3.setPreferredSize(new java.awt.Dimension(110, 64));

        salir.setFont(new java.awt.Font("Lucida Grande", 0, 12));
        salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/exitm.png"))); // NOI18N
        salir.setText("Salir");
        salir.setToolTipText("salir de esta pantalla");
        salir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        salir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel3.add(salir);

        jToolBar1.add(jPanel3);

        getContentPane().add(jToolBar1, java.awt.BorderLayout.PAGE_END);

        jSplitPane1.setDividerLocation(150);
        jSplitPane1.setPreferredSize(new java.awt.Dimension(900, 408));

        jScrollPane1.setBackground(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(tableIcon1);

        jSplitPane1.setRightComponent(jScrollPane1);

        jCalendar1.setPreferredSize(new java.awt.Dimension(300, 231));
        jCalendar1.setWeekOfYearVisible(false);

        cuaderno.setBackground(new java.awt.Color(255, 255, 204));
        cuaderno.setJMenuBar(null);
        cuaderno.setAsYouTypeSpellcheckingEnabled(false);
        cuaderno.setPopupMenuVisible(false);

        save.setText("Almacenar cuaderno");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(save, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 496, Short.MAX_VALUE)
                    .addComponent(cuaderno, javax.swing.GroupLayout.Alignment.LEADING, 0, 0, Short.MAX_VALUE)
                    .addComponent(jCalendar1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 496, Short.MAX_VALUE))
                .addGap(514, 514, 514))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jCalendar1, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cuaderno, javax.swing.GroupLayout.DEFAULT_SIZE, 364, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(save))
        );

        jSplitPane1.setLeftComponent(jPanel5);

        getContentPane().add(jSplitPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void agendarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agendarMouseClicked
        // TODO add your handling code here:
        
        // ESTA CHANCHADA LA VA A ARREGLAR VICTORIA, POR AHORA LLAMO DE ESTA MANERA - PERO NO VA A QUEDAR ASI


        

    }//GEN-LAST:event_agendarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agendar;
    private sferyx.administration.editors.HTMLEditor cuaderno;
    private javax.swing.JLabel fechaHoy;
    private javax.swing.JLabel funcionario;
    private javax.swing.JLabel hora;
    private com.toedter.calendar.JCalendar jCalendar1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JButton pacientes;
    private javax.swing.JButton recargar;
    private javax.swing.JEditorPane resumen;
    private javax.swing.JButton salir;
    private javax.swing.JButton save;
    private com.kcreativa.pitosycornetas.TableIcon tableIcon1;
    private javax.swing.JButton tareas;
    // End of variables declaration//GEN-END:variables

    public Date getFechaElegida() {
        
        return(jCalendar1.getDate());
    }

    public void crearCalendarioListener1(PropertyChangeListener calendarioCambiardoListener) {
        jCalendar1.addPropertyChangeListener(calendarioCambiardoListener);
    }

    public void setFechaActual(Date fechadesde) {
        
        SimpleDateFormat sdf = new SimpleDateFormat("dd-MMM-yyyy");
        
        fechaHoy.setText(sdf.format(fechadesde));
    }

    public String getHoraElegida() {
        
        int fila = tableIcon1.getSelectedRow();
        String val = null;
        if(fila >=0)
         val = (String) tableIcon1.getModel().getValueAt(fila, 3);
        
        return(val);
    }

    public int getTurnoElegido() {
        int fila = tableIcon1.getSelectedRow();
        int val = 1;
        if(fila >=0)
            val = (Integer) tableIcon1.getModel().getValueAt(fila, 5);
        
        return(val);
    }

    public int getDisponibles() {

        int fila = tableIcon1.getSelectedRow();
        int val = 1;
        if(fila >=0)
            val = (Integer) tableIcon1.getModel().getValueAt(fila, 5);

        return(val);
    }

    public void setContenidoCuaderno(String contenido) {
        cuaderno.setContent(contenido);
    }

    public String getContenidoCuaderno(String contenido) {
        return(cuaderno.getContent());
    }

    public void almacenarCuadernoListener(ActionListener al) {

        save.addActionListener(al);
    }

    public void setResumen(String res) {
        resumen.setText(res);
    }

}
