/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * UIVacunas.java
 *
 * Created on 19/07/2011, 01:43:12 PM
 */

package talitakumi.medicos.ui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.HashMap;
import javax.swing.JCheckBox;
import java.text.DateFormat;
import java.util.Date;
import java.text.SimpleDateFormat;
import java.util.Calendar;

/**
 *
 * @author victoria
 */

public class UIVacunas extends javax.swing.JPanel {

    private HashMap <Integer, JCheckBox> vacunas;
    private ActionListener vacunasListener;
    private Integer vacunaelegida;

    /** Creates new form UIVacunas */
    public UIVacunas(int episodio) {

       initComponents();
       
       Date hoy;
       DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
       hoy = new java.util.Date();
       fechaHoy1.setFormats("dd/MM/yyyy");
       fechaHoy1.setDate(hoy);
       fechaHoy1.setEditable(true);

       vacunas = new HashMap <Integer, JCheckBox>();

    }


     public void setVacunasListener(ActionListener al) {

        vacunasListener = al;
     }
    
     public void setPermitirCambiarVacunas(boolean b) {

        for(JCheckBox j : vacunas.values()) {

            j.setEnabled(b);
        }
     }


     public void cambiarEstadoVacuna(Integer consultorio, boolean marcado) {

        JCheckBox jcb = vacunas.get(consultorio);
        jcb.setSelected(marcado);

    }

    public void agregarVacuna(String descripcion, Integer id) {

        if(!vacunas.containsKey(id)) {
           JCheckBox jcb = new JCheckBox();
           jcb.setText(descripcion);
           jcb.setOpaque(false);
           jcb.setFont(new java.awt.Font("Helvetica", 1, 13));
           jcb.addActionListener(vacunasListener);
           jcb.addActionListener(new VacunaTypeado());
           jcb.setName(id+"");
           panel.add(jcb);
           vacunas.put(id, jcb);
 
        }
     }

    public void setGuardarListener(ActionListener al) {
          this.guardar.addActionListener(al);
    }

    public void setNombre(String nombres) {
        this.nombres.setText(nombres);
    }

    public void setApellidos(String Apellidos){
        this.apellidos.setText(Apellidos);
    }

    public void setDomicilio(String Domicilio){
        this.domicilio.setText(Domicilio);
    }

    public void setCiudad(String Ciudad){
       this.ciudad.setText(Ciudad);
    }

    public void setTelefono(String Telefono){
        this.telefono.setText(Telefono);
    }

    public void setCelular(String Celular){
        this.celular.setText(Celular);
    }

    public void setEmail(String email){
        this.email.setText(email);
    }

    public void setFechanacimiento(Date Fechanacimiento){
        this.fechanacimiento.setDate(Fechanacimiento);
    }

    public void setDocumento(int Documento){
        System.out.println("documento es : " +Documento);
        this.documento.setText(Documento+"");
    }

    public void setSexo(char Sexo){
        if(Sexo=='F'){
            femenino.setSelected(true);
            masculino.setSelected(false);
        }else
            if(Sexo=='M'){
                femenino.setSelected(false);
                masculino.setSelected(true);
            }
    }

    public void setEdad(Date fechanacimiento) {

        Calendar hoy = Calendar.getInstance();
        Calendar fechaNac = Calendar.getInstance();

        fechaNac.setTime(fechanacimiento);

    	int years = hoy.get(Calendar.YEAR) - fechaNac.get(Calendar.YEAR);
    	if (hoy.get(Calendar.MONTH) < fechaNac.get(Calendar.MONTH)) years --;
    	if (hoy.get(Calendar.MONTH) == fechaNac.get(Calendar.MONTH) &&
    		hoy.get(Calendar.DATE) < fechaNac.get(Calendar.DATE)	) years --;

        this.edad.setText(years + "");
    }

    private class VacunaTypeado implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent arg0) {

            JCheckBox jcb = (JCheckBox) arg0.getSource();
            vacunaelegida = Integer.parseInt(jcb.getName());

        }
    }

 public Integer getVacunaElegida() {

        return(vacunaelegida);
 }

 public void dispose() {
        //compiled code
        throw new RuntimeException("Compiled Code");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        jLabel36 = new javax.swing.JLabel();
        apellidos = new com.kcreativa.pitosycornetas.KTextBox();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        domicilio = new com.kcreativa.pitosycornetas.KTextBox();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        telefono = new com.kcreativa.pitosycornetas.KTextBox();
        jLabel59 = new javax.swing.JLabel();
        celular = new com.kcreativa.pitosycornetas.KTextBox();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        masculino = new javax.swing.JRadioButton();
        jLabel62 = new javax.swing.JLabel();
        fechanacimiento = new org.jdesktop.swingx.JXDatePicker();
        femenino = new javax.swing.JRadioButton();
        email = new com.kcreativa.pitosycornetas.KTextBox();
        jLabel20 = new javax.swing.JLabel();
        edad = new com.kcreativa.pitosycornetas.KTextBox();
        jLabel63 = new javax.swing.JLabel();
        estadocivil = new javax.swing.JComboBox();
        jLabel65 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        laboratorio = new javax.swing.JRadioButton();
        ciudad = new javax.swing.JTextField();
        nombres = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        fechaHoy1 = new org.jdesktop.swingx.JXDatePicker();
        documento = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        panelvacunas = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        panel = new javax.swing.JPanel();
        cancelar = new javax.swing.JButton();
        guardar = new javax.swing.JButton();

        setLayout(null);

        jPanel7.setBackground(new java.awt.Color(240, 240, 240));
        jPanel7.setForeground(new java.awt.Color(240, 240, 240));
        jPanel7.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel36.setText("APELLIDOS");

        apellidos.setFont(new java.awt.Font("Lucida Grande", 1, 13));

        jLabel55.setText("NOMBRES");

        jLabel56.setText("DOMICILIO");

        domicilio.setFont(new java.awt.Font("Lucida Grande", 1, 13));

        jLabel57.setText("CIUDAD");

        jLabel58.setText("TELÉFONO");

        telefono.setFont(new java.awt.Font("Lucida Grande", 1, 13));

        jLabel59.setText("CELULAR");

        celular.setFont(new java.awt.Font("Lucida Grande", 1, 13));

        jLabel60.setText("EMAIL");

        jLabel61.setText("SEXO");

        masculino.setSelected(true);
        masculino.setText("Masculino");

        jLabel62.setText("FECHA DE NACIMIENTO");

        femenino.setText("Femenino");

        email.setText("@");
        email.setFont(new java.awt.Font("Lucida Grande", 1, 13));

        jLabel20.setText("EDAD");

        jLabel63.setText("ESTADO CIVIL");

        estadocivil.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SOLTERO", "CASADO", "DIVORCIADO", "VIUDO" }));

        jLabel65.setFont(new java.awt.Font("Arial", 3, 18));
        jLabel65.setText("DATOS PERSONALES");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Examen de Ingreso", "Examen de Egreso", "Chequeo Preventivo de Salud", "Psico Técnico Chofer" }));

        jLabel2.setText("SOLICITADO POR: ");

        laboratorio.setText("LABORATORIO");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel63)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(estadocivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116, Short.MAX_VALUE)
                                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel62)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fechanacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel61)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(masculino)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(femenino)))
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(edad, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(jLabel2)))
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(laboratorio)
                                .addGap(209, 209, 209))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel65)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel7Layout.createSequentialGroup()
                                        .addComponent(jLabel36)
                                        .addGap(6, 6, 6)
                                        .addComponent(apellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel55)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(nombres, javax.swing.GroupLayout.DEFAULT_SIZE, 407, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel7Layout.createSequentialGroup()
                                        .addComponent(jLabel58)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(telefono, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel59)
                                        .addGap(18, 18, 18)
                                        .addComponent(celular, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel60)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel7Layout.createSequentialGroup()
                                        .addComponent(jLabel56)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(domicilio, javax.swing.GroupLayout.DEFAULT_SIZE, 524, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel57, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ciudad, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(19, 19, 19)))
                        .addGap(199, 199, 199)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel65)
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel36)
                    .addComponent(apellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel55)
                    .addComponent(nombres, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel56)
                    .addComponent(domicilio, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel57)
                    .addComponent(ciudad, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel58)
                    .addComponent(jLabel59)
                    .addComponent(telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(celular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel60)
                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel62)
                    .addComponent(fechanacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel61)
                    .addComponent(masculino)
                    .addComponent(femenino)
                    .addComponent(jLabel20)
                    .addComponent(edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(laboratorio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel63)
                    .addComponent(estadocivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(jPanel7);
        jPanel7.setBounds(0, 96, 877, 191);

        jLabel1.setFont(new java.awt.Font("Lucida Sans", 0, 24));
        jLabel1.setForeground(new java.awt.Color(0, 51, 153));
        jLabel1.setText("VACUNAS");
        jLabel1.setMaximumSize(new java.awt.Dimension(310, 29));
        jLabel1.setMinimumSize(new java.awt.Dimension(310, 29));
        jLabel1.setPreferredSize(new java.awt.Dimension(310, 29));
        add(jLabel1);
        jLabel1.setBounds(295, 28, 291, 29);

        jLabel3.setText("FECHA");
        add(jLabel3);
        jLabel3.setBounds(360, 70, 70, 17);

        fechaHoy1.setFormats("dd/mm/aaaa");
        fechaHoy1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fechaHoy1ActionPerformed(evt);
            }
        });
        add(fechaHoy1);
        fechaHoy1.setBounds(432, 63, 130, 27);
        add(documento);
        documento.setBounds(710, 63, 132, 27);

        jLabel4.setText("DOCUMENTO");
        add(jLabel4);
        jLabel4.setBounds(600, 70, 110, 17);

        panelvacunas.setBackground(new java.awt.Color(225, 225, 225));

        jLabel5.setText("VACUNAS");

        panel.setBackground(new java.awt.Color(255, 255, 255));
        panel.setLayout(new javax.swing.BoxLayout(panel, javax.swing.BoxLayout.Y_AXIS));

        javax.swing.GroupLayout panelvacunasLayout = new javax.swing.GroupLayout(panelvacunas);
        panelvacunas.setLayout(panelvacunasLayout);
        panelvacunasLayout.setHorizontalGroup(
            panelvacunasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelvacunasLayout.createSequentialGroup()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, 730, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(70, Short.MAX_VALUE))
        );
        panelvacunasLayout.setVerticalGroup(
            panelvacunasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelvacunasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelvacunasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        add(panelvacunas);
        panelvacunas.setBounds(0, 339, 877, 350);

        cancelar.setText("CANCELAR");
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });
        add(cancelar);
        cancelar.setBounds(652, 700, 110, 30);

        guardar.setText("GUARDAR");
        add(guardar);
        guardar.setBounds(520, 700, 110, 29);
    }// </editor-fold>//GEN-END:initComponents

    private void fechaHoy1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fechaHoy1ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_fechaHoy1ActionPerformed

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        // TODO add your handling code here:

        this.setVisible(false);
}//GEN-LAST:event_cancelarActionPerformed

   
    public void vaciarFormulario(){

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.kcreativa.pitosycornetas.KTextBox apellidos;
    private javax.swing.JButton cancelar;
    private com.kcreativa.pitosycornetas.KTextBox celular;
    private javax.swing.JTextField ciudad;
    private javax.swing.JTextField documento;
    private com.kcreativa.pitosycornetas.KTextBox domicilio;
    private com.kcreativa.pitosycornetas.KTextBox edad;
    private com.kcreativa.pitosycornetas.KTextBox email;
    private javax.swing.JComboBox estadocivil;
    private org.jdesktop.swingx.JXDatePicker fechaHoy1;
    private org.jdesktop.swingx.JXDatePicker fechanacimiento;
    private javax.swing.JRadioButton femenino;
    private javax.swing.JButton guardar;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JRadioButton laboratorio;
    private javax.swing.JRadioButton masculino;
    private javax.swing.JTextField nombres;
    private javax.swing.JPanel panel;
    private javax.swing.JPanel panelvacunas;
    private com.kcreativa.pitosycornetas.KTextBox telefono;
    // End of variables declaration//GEN-END:variables

}
