/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * UIListaDePrecios.java
 *
 * Created on 13-abr-2010, 16:00:35
 */

package talitakumiadmin.administracion.ui;

import java.awt.event.ActionListener;
import java.awt.event.MouseListener;
import java.util.HashMap;
import java.util.List;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;


/**
 *
 * @author rupertus
 */
public class UIClientes extends javax.swing.JPanel {

    /** Creates new form UIListaDePrecios */
    public UIClientes() {
        initComponents();
        
        clientes.setAutoCreateRowSorter(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        clientes = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        nombreLabel = new javax.swing.JLabel();
        idLabel = new javax.swing.JLabel();
        departamentoLabel = new javax.swing.JLabel();
        webLabel = new javax.swing.JLabel();
        telefonosLabel = new javax.swing.JLabel();
        ciudadLabel = new javax.swing.JLabel();
        rutLabel = new javax.swing.JLabel();
        domicilioLabel = new javax.swing.JLabel();
        habilitadoLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        domicilioFiscalLabel = new javax.swing.JLabel();
        razonSocialLabel = new javax.swing.JLabel();
        observacionesLabel = new javax.swing.JLabel();
        habilitadoLabel3 = new javax.swing.JLabel();
        habilitadoLabel2 = new javax.swing.JLabel();
        habilitadoLabel1 = new javax.swing.JLabel();
        emailField = new javax.swing.JTextField();
        webField = new javax.swing.JTextField();
        departamentoField = new javax.swing.JTextField();
        domicilioFiscalField = new javax.swing.JTextField();
        habilitadoField = new javax.swing.JTextField();
        razonSocialField = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        observaciones = new javax.swing.JTextArea();
        idField = new javax.swing.JTextField();
        nombreField = new javax.swing.JTextField();
        rutField = new javax.swing.JTextField();
        domicilioField = new javax.swing.JTextField();
        telefonosField = new javax.swing.JTextField();
        ciudadField = new javax.swing.JTextField();
        importeContrato = new javax.swing.JTextField();
        facturar = new javax.swing.JTextField();
        facturaMesActual = new javax.swing.JTextField();
        almacenar = new javax.swing.JButton();
        habilitadoLabel4 = new javax.swing.JLabel();
        emisor = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        nuevo = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jSplitPane1.setDividerLocation(300);

        clientes.setAutoCreateRowSorter(true);
        clientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        jScrollPane1.setViewportView(clientes);

        jSplitPane1.setLeftComponent(jScrollPane1);

        jScrollPane2.setBackground(new java.awt.Color(204, 204, 204));

        nombreLabel.setText("Nombre:");

        idLabel.setText("Id:");

        departamentoLabel.setText("Departamento:");

        webLabel.setText("Web:");

        telefonosLabel.setText("Telefonos:");

        ciudadLabel.setText("Ciudad:");

        rutLabel.setText("Rut:");

        domicilioLabel.setText("Domicilio:");

        habilitadoLabel.setText("Habilitado:");

        emailLabel.setText("Email:");

        domicilioFiscalLabel.setText("Domicilio Fiscal:");

        razonSocialLabel.setText("Razon Social:");

        observacionesLabel.setText("Observaciones:");

        habilitadoLabel3.setText("Factura mes actual");

        habilitadoLabel2.setText("Importe contrato");

        habilitadoLabel1.setText("Facturar");

        observaciones.setColumns(20);
        observaciones.setRows(5);
        jScrollPane3.setViewportView(observaciones);

        almacenar.setText("Almacenar");

        habilitadoLabel4.setText("Emisor");

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel2Layout.createSequentialGroup()
                        .add(20, 20, 20)
                        .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanel2Layout.createSequentialGroup()
                                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(idLabel)
                                    .add(nombreLabel)
                                    .add(rutLabel)
                                    .add(domicilioLabel)
                                    .add(telefonosLabel)
                                    .add(ciudadLabel)
                                    .add(departamentoLabel)
                                    .add(razonSocialLabel)
                                    .add(domicilioFiscalLabel)
                                    .add(emailLabel)
                                    .add(webLabel))
                                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                    .add(jPanel2Layout.createSequentialGroup()
                                        .add(10, 10, 10)
                                        .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                            .add(org.jdesktop.layout.GroupLayout.LEADING, nombreField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 655, Short.MAX_VALUE)
                                            .add(org.jdesktop.layout.GroupLayout.LEADING, razonSocialField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 655, Short.MAX_VALUE)
                                            .add(org.jdesktop.layout.GroupLayout.LEADING, idField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 72, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                            .add(org.jdesktop.layout.GroupLayout.LEADING, rutField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 160, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                            .add(org.jdesktop.layout.GroupLayout.LEADING, domicilioField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 655, Short.MAX_VALUE)
                                            .add(org.jdesktop.layout.GroupLayout.LEADING, domicilioFiscalField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 655, Short.MAX_VALUE)
                                            .add(org.jdesktop.layout.GroupLayout.LEADING, telefonosField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 246, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                            .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                                                .add(org.jdesktop.layout.GroupLayout.LEADING, departamentoField)
                                                .add(org.jdesktop.layout.GroupLayout.LEADING, ciudadField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                                                .add(org.jdesktop.layout.GroupLayout.LEADING, webField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 396, Short.MAX_VALUE)
                                                .add(org.jdesktop.layout.GroupLayout.LEADING, emailField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 239, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                                .add(org.jdesktop.layout.GroupLayout.LEADING, habilitadoField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 31, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                                    .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel2Layout.createSequentialGroup()
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                            .add(facturar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 31, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                            .add(jScrollPane3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 655, Short.MAX_VALUE)))))
                            .add(observacionesLabel)
                            .add(habilitadoLabel)
                            .add(habilitadoLabel1)))
                    .add(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .add(habilitadoLabel2)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(importeContrato, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 132, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(habilitadoLabel3)
                            .add(habilitadoLabel4))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(emisor, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 31, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(facturaMesActual, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 31, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(193, 193, 193)
                        .add(almacenar)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .add(45, 45, 45)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(idLabel)
                    .add(idField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(nombreLabel)
                    .add(nombreField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(razonSocialLabel)
                    .add(razonSocialField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(rutLabel)
                    .add(rutField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(domicilioFiscalLabel)
                    .add(domicilioFiscalField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(domicilioLabel)
                    .add(domicilioField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(telefonosLabel)
                    .add(telefonosField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(ciudadLabel)
                    .add(ciudadField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(departamentoLabel)
                    .add(jPanel2Layout.createSequentialGroup()
                        .add(departamentoField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(webField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(webLabel))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(emailField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(emailLabel))))
                .add(28, 28, 28)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(habilitadoLabel)
                    .add(habilitadoField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(observacionesLabel)
                    .add(jScrollPane3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 76, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jPanel2Layout.createSequentialGroup()
                        .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanel2Layout.createSequentialGroup()
                                .add(13, 13, 13)
                                .add(habilitadoLabel1))
                            .add(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(facturar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                        .add(18, 18, 18)
                        .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(habilitadoLabel2)
                            .add(importeContrato, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(habilitadoLabel3)
                            .add(facturaMesActual, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(habilitadoLabel4)
                            .add(emisor, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .add(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(almacenar)
                        .addContainerGap())))
        );

        jScrollPane2.setViewportView(jPanel2);

        jSplitPane1.setRightComponent(jScrollPane2);

        add(jSplitPane1, java.awt.BorderLayout.CENTER);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        nuevo.setText("Nuevo");
        jPanel1.add(nuevo);

        add(jPanel1, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton almacenar;
    private javax.swing.JTextField ciudadField;
    private javax.swing.JLabel ciudadLabel;
    private javax.swing.JTable clientes;
    private javax.swing.JTextField departamentoField;
    private javax.swing.JLabel departamentoLabel;
    private javax.swing.JTextField domicilioField;
    private javax.swing.JTextField domicilioFiscalField;
    private javax.swing.JLabel domicilioFiscalLabel;
    private javax.swing.JLabel domicilioLabel;
    private javax.swing.JTextField emailField;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField emisor;
    private javax.swing.JTextField facturaMesActual;
    private javax.swing.JTextField facturar;
    private javax.swing.JTextField habilitadoField;
    private javax.swing.JLabel habilitadoLabel;
    private javax.swing.JLabel habilitadoLabel1;
    private javax.swing.JLabel habilitadoLabel2;
    private javax.swing.JLabel habilitadoLabel3;
    private javax.swing.JLabel habilitadoLabel4;
    private javax.swing.JTextField idField;
    private javax.swing.JLabel idLabel;
    private javax.swing.JTextField importeContrato;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTextField nombreField;
    private javax.swing.JLabel nombreLabel;
    private javax.swing.JButton nuevo;
    private javax.swing.JTextArea observaciones;
    private javax.swing.JLabel observacionesLabel;
    private javax.swing.JTextField razonSocialField;
    private javax.swing.JLabel razonSocialLabel;
    private javax.swing.JTextField rutField;
    private javax.swing.JLabel rutLabel;
    private javax.swing.JTextField telefonosField;
    private javax.swing.JLabel telefonosLabel;
    private javax.swing.JTextField webField;
    private javax.swing.JLabel webLabel;
    // End of variables declaration//GEN-END:variables


    public void setModelListaConsultas(DefaultTableModel dftm) {

        clientes.setModel(dftm);
    }

    public void setAnchoColumna(int idx, int ancho) {
        clientes.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        TableColumn col = clientes.getColumnModel().getColumn(idx);
        col.setPreferredWidth(ancho);

    }

    public void addAlmacenarListener(ActionListener clientesListener) {

        almacenar.addActionListener(clientesListener);
    }

    public void addClienteListener(MouseListener clientesListener) {

        clientes.addMouseListener(clientesListener);
    }

    public int getClienteElegido() {

        int resp = 0;

        int x = clientes.getSelectedColumn();
        int y = clientes.getSelectedRow();

        resp = (Integer) clientes.getValueAt(y, 0);

        return(resp);
    }

    public int[] getListaClientes() {

        return(clientes.getSelectedRows());
    }

    public int getClienteEnRow(int i) {

        return((Integer)clientes.getValueAt(i, 0));
    }

    public void setID(Integer id) {
       this.idField.setText(id+"");
    }

    public void setCiudad(String ciudad) {
        this.ciudadField.setText(ciudad);
    }

    public void setDepartamento(String departamento) {
        this.departamentoField.setText(departamento);
    }

    public void setDomicilio(String domicilio) {
        this.domicilioField.setText(domicilio);
    }

    public void setDomicilioFiscal(String domicilioFiscal) {
        this.domicilioFiscalField.setText(domicilioFiscal);
    }

    public void setEmail(String email) {
        this.emailField.setText(email);
    }

    public void setFacturar(char facturar) {
        this.facturar.setText(facturar+"");
    }

    public void setFacturaMismoMes(char facturarMismoMes) {
        this.facturaMesActual.setText(facturarMismoMes+"");
    }

    public void setHabilitado(char habilitado) {
        this.habilitadoField.setText(habilitado+"");
    }

    public void setImporteContrato(Float importeContrato) {
        this.importeContrato.setText(importeContrato+"");
    }

    public void setNombre(String nombre) {
        this.nombreField.setText(nombre);
    }

    public void setObservaciones(String observaciones) {
        this.observaciones.setText(observaciones);
    }

    public void setRazonSocial(String razonSocial) {
        this.razonSocialField.setText(razonSocial);
    }

    public void setRut(String rut) {
        this.rutField.setText(rut);
    }

    public void setTelefonos(String telefonos) {
        this.telefonosField.setText(telefonos);
    }

    public void setWeb(String web) {
        this.webField.setText(web);
    }

    public void addNuevoListener(ActionListener nuevoListener) {
        nuevo.addActionListener(nuevoListener);
    }

    public String getCiudad() {
        return(ciudadField.getText());
    }

    public String getDepartamento() {
        return(departamentoField.getText());
    }

    public String getDomicilio() {
        return(domicilioField.getText());
    }

    public String getDomicilioFiscal() {
        return(domicilioFiscalField.getText());
    }

    public String getEmail() {
        return(emailField.getText());
    }

    public char getFacturar() {
        if(facturar.getText().equals("S"))
            return('S');
        else
            return('N');
    }

    public char getFacturarMismoMes() {
        if(facturaMesActual.getText().equals("S"))
            return('S');
        else
            return('N');
    }

    public char getHabilitado() {
        if(habilitadoField.getText().equals("S"))
            return('S');
        else
            return('N');
    }

    public Integer getId() {
        return(Integer.parseInt(idField.getText()));
    }

    public Float getImporteContrato() {
        return(Float.parseFloat(importeContrato.getText()));
    }

    public String getNombre() {
        return(nombreField.getText());
    }

    public String getObservaciones() {
        return(observaciones.getText());
    }

    public String getRazonSocial() {
        return(razonSocialField.getText());
    }

    public String getRut() {
        return(rutField.getText());
    }

    public String getTelefonos() {
        return(telefonosField.getText());
    }

    public String getWeb() {
        return(webField.getText());
    }

    public void setEmisor(Integer emisor) {
        this.emisor.setText(emisor+"");
    }

    public Integer getEmisor() {

        Integer emisor = 0;
        if(this.emisor.getText().length()>0) {
            emisor = Integer.parseInt(this.emisor.getText());
        }
        return(emisor);
    }

}
