/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * UIListaDePrecios.java
 *
 * Created on 13-abr-2010, 16:00:35
 */

package talitakumiadmin.administracion.ui;

import java.awt.event.ActionListener;
import java.beans.PropertyChangeListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rupertus
 */
public class UIFeriadosController extends javax.swing.JPanel {

    /** Creates new form UIListaDePrecios */
    public UIFeriadosController() {
        initComponents();

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        almacenar = new javax.swing.JButton();
        jCalendar1 = new com.toedter.calendar.JCalendar();
        jLabel1 = new javax.swing.JLabel();
        cerrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        almacenar.setText("Borrar");
        add(almacenar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, -1, -1));

        jCalendar1.setPreferredSize(new java.awt.Dimension(300, 231));
        jCalendar1.setWeekOfYearVisible(false);
        add(jCalendar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 340, 260));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Fecha");
        jLabel1.setOpaque(true);
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 130, 30));

        cerrar.setText("Cerrar");
        add(cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 280, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Fecha"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, 190, 260));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton almacenar;
    private javax.swing.JButton cerrar;
    private com.toedter.calendar.JCalendar jCalendar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    public void addAlmacenarListener(ActionListener clientesListener) {

        almacenar.addActionListener(clientesListener);
    }

    public Date getFecha() {

        return(jCalendar1.getDate());
    }

    public void setFecha(Date date) {

        jCalendar1.setDate(date);
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        jLabel1.setText(sdf.format(date));
    }

    public void addCerrarListener(ActionListener cancelarListener) {

        cerrar.addActionListener(cancelarListener);
    }

    public void setModeloFeriados(DefaultTableModel dftm) {
        jTable1.setModel(dftm);
    }

    public void crearCalendarioListener1(PropertyChangeListener calendarioCambiardoListener) {
        jCalendar1.addPropertyChangeListener(calendarioCambiardoListener);
    }
}
