/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * UIListaDePrecios.java
 *
 * Created on 13-abr-2010, 16:00:35
 */

package talitakumiadmin.administracion.ui;

import java.awt.event.ActionListener;
import java.util.Date;

/**
 *
 * @author rupertus
 */
public class UINotasAgenda extends javax.swing.JPanel {

    /** Creates new form UIListaDePrecios */
    public UINotasAgenda() {
        initComponents();

        editor.wrapNewLineIntoBR(true);
        editor.setSourceEditorVisible(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        almacenar = new javax.swing.JButton();
        panelCuaderno = new javax.swing.JPanel();
        editor = new sferyx.administration.editors.HTMLEditor();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        almacenar.setText("Almacenar");
        jPanel1.add(almacenar);

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        editor.setAsYouTypeSpellcheckingEnabled(false);
        editor.setMenuBar(null);

        org.jdesktop.layout.GroupLayout panelCuadernoLayout = new org.jdesktop.layout.GroupLayout(panelCuaderno);
        panelCuaderno.setLayout(panelCuadernoLayout);
        panelCuadernoLayout.setHorizontalGroup(
            panelCuadernoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(panelCuadernoLayout.createSequentialGroup()
                .add(editor, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 938, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelCuadernoLayout.setVerticalGroup(
            panelCuadernoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(editor, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 473, Short.MAX_VALUE)
        );

        add(panelCuaderno, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton almacenar;
    private sferyx.administration.editors.HTMLEditor editor;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel panelCuaderno;
    // End of variables declaration//GEN-END:variables

    public void addAlmacenarListener(ActionListener clientesListener) {

        almacenar.addActionListener(clientesListener);
    }

    public void setContenidoCuaderno(String txt) {

        editor.setContent_(txt);
    }

    public String getContenidoCuaderno() {
        return(editor.getContent());
    }


}
