/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * UIListaDePrecios.java
 *
 * Created on 13-abr-2010, 16:00:35
 */

package talitakumiadmin.administracion.ui;

import java.awt.event.ActionListener;
import java.awt.event.MouseListener;
import java.text.DecimalFormat;
import java.text.ParseException;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rupertus
 */
public class UIUsuarios extends javax.swing.JPanel {

    /** Creates new form UIListaDePrecios */
    public UIUsuarios() {
        initComponents();

        tablaEstudios.setAutoCreateRowSorter(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollEstudios = new javax.swing.JScrollPane();
        tablaEstudios = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        cargo = new javax.swing.JTextField();
        usuario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        almacenar = new javax.swing.JButton();
        cerrar = new javax.swing.JButton();
        nivel = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        funcionario = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        medico = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        rol = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        clave = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaEstudios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scrollEstudios.setViewportView(tablaEstudios);

        add(scrollEstudios, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 740, 290));

        jLabel1.setText("Cargo");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 90, 20));

        cargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargoActionPerformed(evt);
            }
        });
        add(cargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 340, 500, 30));

        usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioActionPerformed(evt);
            }
        });
        add(usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, 180, 30));

        jLabel2.setText("eMail");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 370, 40, 20));

        jLabel3.setText("Nivel");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 90, 20));

        almacenar.setText("Almacenar");
        add(almacenar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 430, -1, 40));

        cerrar.setText("Cerrar");
        add(cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 440, -1, -1));
        add(nivel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 400, 120, -1));

        jLabel4.setText("Funcionario");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 90, 20));

        funcionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                funcionarioActionPerformed(evt);
            }
        });
        add(funcionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 370, 120, 30));

        jLabel6.setText("Medico");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 370, 50, 20));

        medico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medicoActionPerformed(evt);
            }
        });
        add(medico, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 370, 100, 30));

        jLabel7.setText("Rol");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 400, 40, 20));

        rol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rolActionPerformed(evt);
            }
        });
        add(rol, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 400, 180, 30));

        jLabel5.setText("Usuario");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, -1, -1));

        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });
        add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 370, 180, 30));

        clave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                claveActionPerformed(evt);
            }
        });
        add(clave, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 310, 180, 30));

        jLabel8.setText("Clave");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 320, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void cargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cargoActionPerformed

    private void usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usuarioActionPerformed

    private void funcionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_funcionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_funcionarioActionPerformed

    private void medicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_medicoActionPerformed

    private void rolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rolActionPerformed

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void claveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_claveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_claveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton almacenar;
    private javax.swing.JTextField cargo;
    private javax.swing.JButton cerrar;
    private javax.swing.JTextField clave;
    private javax.swing.JTextField email;
    private javax.swing.JTextField funcionario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField medico;
    private javax.swing.JTextField nivel;
    private javax.swing.JTextField rol;
    private javax.swing.JScrollPane scrollEstudios;
    private javax.swing.JTable tablaEstudios;
    private javax.swing.JTextField usuario;
    // End of variables declaration//GEN-END:variables

    public void addAlmacenarListener(ActionListener clientesListener) {

        almacenar.addActionListener(clientesListener);
    }

    public void addCerrarListener(ActionListener cancelarListener) {

        cerrar.addActionListener(cancelarListener);
    }

    public void setModeloFeriados(DefaultTableModel dftm) {
        tablaEstudios.setModel(dftm);
    }

    public String getUsuarioElegido() {
        
        String id = "";
        
        int i = tablaEstudios.getSelectedRow();
        if(i>=0) {

            id = (String) tablaEstudios.getValueAt(i, 0);
        }
        
        return(id);
    }

    public void addEstudioElegidoListener(MouseListener estudioElegidoListener) {

        tablaEstudios.addMouseListener(estudioElegidoListener);
    }

    public void setDescripcion(String descripcion) {

        this.cargo.setText(descripcion);
    }

    public void setTagEstudio(String tagEstudio) {

        this.usuario.setText(tagEstudio);
    }

    public void setPrecioBase(float preciobase) {

        this.nivel.setText(preciobase+"");
    }

    public String getDescricpion() {

        return(cargo.getText());
    }

    public Float getPrecioBase() throws ParseException {

        String txt = nivel.getText();

        DecimalFormat df = new DecimalFormat("0.00");

        Number n = df.parse(txt);
        n.floatValue();

        return(Float.parseFloat(txt));
    }

    public Integer getMedico() {

        if(medico.getText().equals("")) {
            
            medico.setText("0");
        }
        return(Integer.parseInt(medico.getText()));
    }

    public void setMedico(String f) {

        medico.setText(f);
    }

    public void setTipoActividad(String descripcion) {
        usuario.setText(descripcion);
    }

    public void setCargo(String cargo) {
        this.cargo.setText(cargo);
    }

    public void setFuncionario(Integer funcionario) {
        
        this.funcionario.setText(funcionario+"");
    }

    public void setEmail(String email) {
        
        this.email.setText(email);
    }

    public void setNivel(int nivel) {
        
        this.nivel.setText(nivel+"");
    }

    public void setRol(String rol) {
        
        this.rol.setText(rol);
    }

    public void setUsuario(String usuario) {
        
        this.usuario.setText(usuario);
    }

    public void setClave(String clave) {
        
        this.clave.setText(clave);
    }

    public void setMedico(int medico) {
        
        this.medico.setText(medico+"");
    }

    public String getCargo() {
        
        return(this.cargo.getText());
    }

    public Integer getFuncionario() {
        
        return(Integer.parseInt(this.funcionario.getText()));
    }

    public String getEmail() {
        return(this.email.getText());
    }

    public int getNivel() {
        return(Integer.parseInt(this.nivel.getText()));
    }

    public String getRol() {
        return(this.rol.getText());
    }

    public String getUsuario() {
        return(this.usuario.getText());
    }

    public String getClave() {
        return(this.clave.getText());
    }

}
