/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * UIInformes.java
 *
 * Created on 26-ene-2009, 8:22:57
 */

package talitakumi.informes.ui;

import java.awt.event.MouseListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import talitakumi.model.core.Clientes;

/**
 *
 * @author rupertus
 */
public class UIInformes extends javax.swing.JFrame {

    String fechaDesde, fechaHasta, tarea;
    
    /** Creates new form UIInformes */
    public UIInformes() {


        initComponents();

        tarea = "";
        fechadesde.setFormats(new SimpleDateFormat("dd-MM-yyyy"));
        fechahasta.setFormats(new SimpleDateFormat("dd-MM-yyyy"));

        fechadesde.setDate(new Date());
        fechahasta.setDate(new Date());
    }

    public void crearInformeListener(MouseListener tareaListener) {

        tablatareas.addMouseListener((MouseListener) tareaListener);
    }

    public String getTareaElegida() {

        int c = this.tablatareas.getSelectedRow();

        return((String)tablatareas.getValueAt(c, 1));

    }

    public void limpiar() {

    }

    public void setAnchoColumna(int i, int ancho) {

        tablatareas.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        TableColumn col = tablatareas.getColumnModel().getColumn(i);
        col.setPreferredWidth(ancho);
    }

    public Date getFechaDesde() {

        return(fechadesde.getDate());
    }

    public Date getFechaHasta() {

        return(fechahasta.getDate());
    }

    public void setModeloTabla(DefaultTableModel dftm) {

        this.tablatareas.setModel(dftm);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablatareas = new com.kcreativa.pitosycornetas.TableIcon();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        fechadesde = new org.jdesktop.swingx.JXDatePicker();
        fechahasta = new org.jdesktop.swingx.JXDatePicker();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        clientes = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        academias = new javax.swing.JComboBox();
        TipoPago = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        uiemisor = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Informes generales");
        setResizable(false);

        jScrollPane1.setViewportView(tablatareas);

        jButton1.setText("Cerrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Informes generales");

        jLabel2.setText("Fecha desde");

        jLabel3.setText("Fecha hasta");

        jLabel4.setText("Cliente");

        clientes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        clientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientesActionPerformed(evt);
            }
        });

        jLabel5.setText("Procedencia");

        academias.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        TipoPago.setEditable(true);
        TipoPago.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "CREDITO", "CONTADO", "AMBAS" }));

        jLabel6.setText("Tipo de Pago");

        uiemisor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--TODOS--", "Gaston Moratorio", "Medicina Laboral", "Raul Barañano" }));

        jLabel7.setText("Emisor");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 627, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 627, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TipoPago, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(fechahasta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(fechadesde, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel7))
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(academias, 0, 183, Short.MAX_VALUE)
                                    .addComponent(clientes, 0, 183, Short.MAX_VALUE)
                                    .addComponent(uiemisor, 0, 183, Short.MAX_VALUE))
                                .addGap(75, 75, 75))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(34, 34, 34)))))
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(clientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(fechadesde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(academias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(fechahasta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(TipoPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(uiemisor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addContainerGap(52, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-671)/2, (screenSize.height-483)/2, 671, 483);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void clientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clientesActionPerformed

    /**
    * @param args the command line arguments
    */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox TipoPago;
    private javax.swing.JComboBox academias;
    private javax.swing.JComboBox clientes;
    private org.jdesktop.swingx.JXDatePicker fechadesde;
    private org.jdesktop.swingx.JXDatePicker fechahasta;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private com.kcreativa.pitosycornetas.TableIcon tablatareas;
    private javax.swing.JComboBox uiemisor;
    // End of variables declaration//GEN-END:variables

    public void setListaProcedencias(DefaultComboBoxModel procedencias) {

        clientes.setModel(procedencias);
    }

    public void setModeloProcedencias(DefaultComboBoxModel dcbm) {
        clientes.setModel(dcbm);
    }

    public int getCliente() {

        return(clientes.getSelectedIndex());
    }

    public void setModeloAcademias(DefaultComboBoxModel dcbm) {
        academias.setModel(dcbm);
    }

    public int getProcedencia() {
        return(academias.getSelectedIndex());
    }

    public void setModeloTipo(DefaultComboBoxModel dcbm) {
        TipoPago.setModel(dcbm);
    }

    public String getTipoPago() {
        
        return(String) (TipoPago.getSelectedItem());
    }

    public String getUiemisor() {


        String x = (String) (uiemisor.getSelectedItem());

        return(x);
    }

   

}
