/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FrameEleccionTareas.java
 *
 * Created on 20-nov-2008, 8:37:49
 */

package view;

import java.awt.event.MouseListener;
import javax.swing.JTable;
import javax.swing.table.TableColumn;
import javax.swing.table.TableModel;

/**
 *
 * @author rupertus
 */
public class FrameEleccionTareas extends javax.swing.JFrame {

    /** Creates new form FrameEleccionTareas */
    public FrameEleccionTareas() {
        initComponents();

        this.setUndecorated(true);
        tablatareas.setShowVerticalLines(true);
        tablatareas.setRowHeight(32);
    }

    public void crearTareaListener(MouseListener tareaListener) {

        tablatareas.addMouseListener((MouseListener) tareaListener);
    }

    public String getTareaElegida() {

        int c = this.tablatareas.getSelectedRow();
        
        return((String)tablatareas.getValueAt(c, 1));
        
    }

    public void limpiar() {
        
    }

    public void setAnchoColumna(int i, int ancho) {

        tablatareas.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        TableColumn col = tablatareas.getColumnModel().getColumn(i);
        col.setPreferredWidth(ancho);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        scrolltareas = new javax.swing.JScrollPane();
        tablatareas = new com.kcreativa.pitosycornetas.TableIcon();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ingreso al sistemas");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logomedilab150x94.jpg"))); // NOI18N
        jPanel1.add(jLabel1);

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 24));
        jLabel2.setForeground(new java.awt.Color(0, 51, 153));
        jLabel2.setText("Ingreso al sistema");
        jPanel1.add(jLabel2);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        tablatareas.setGridColor(new java.awt.Color(204, 204, 204));
        scrolltareas.setViewportView(tablatareas);

        getContentPane().add(scrolltareas, java.awt.BorderLayout.CENTER);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-643)/2, (screenSize.height-500)/2, 643, 500);
    }// </editor-fold>//GEN-END:initComponents


    public void setModeloTabla(TableModel tm) {

        tablatareas.setModel(tm);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane scrolltareas;
    private com.kcreativa.pitosycornetas.TableIcon tablatareas;
    // End of variables declaration//GEN-END:variables

}
