/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PanelMedilab.java
 *
 * Created on 16-nov-2008, 12:52:05
 */

package view;

/**
 *
 * @author rupertus
 */
public class PanelMedilab extends javax.swing.JPanel {

    /** Creates new form PanelMedilab */
    public PanelMedilab() {
        initComponents();
    }

    public void setConsultorio(String consultorio) {
        this.consultorio.setText(consultorio);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        consultorio = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.BorderLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo.jpg"))); // NOI18N
        add(jLabel1, java.awt.BorderLayout.CENTER);

        consultorio.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        consultorio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(consultorio, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel consultorio;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

}
