/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * UIConsultorio.java
 *
 * Created on 16-nov-2008, 11:15:37
 */

package view;

import java.awt.Font;
import java.awt.Rectangle;
import java.awt.event.ActionListener;
import java.awt.event.KeyListener;
import java.awt.event.MouseListener;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;;

/**
 *
 * @author rupertus
 */
public class UIPanelMantenimiento extends javax.swing.JFrame {

    int dividerlocation;

    /** Creates new form UIConsultorio */
    public UIPanelMantenimiento() {
        initComponents();

        jToolBar1.setVisible(true);
        dividerlocation = this.jSplitPane1.getDividerLocation();
    }

    public void apuntarFilaAgenda(int i) {
        jTableAgenda.setRowSelectionInterval(i, i);
        Rectangle rect = jTableAgenda.getCellRect(i, 0, true);
        jTableAgenda.scrollRectToVisible(rect);

    }

    public String getBuscar() {

        return(buscar.getText().toUpperCase());
    }

    public void resetVista() {

        jSplitPane1.setDividerLocation(dividerlocation);
        scrollUtil.getVerticalScrollBar().setValue(0);
    }

    public void salirListener(ActionListener al) {

        botonSalir.addActionListener(al);
    }

    public void crearAgendaListener(MouseListener al) {

        jTableAgenda.addMouseListener((MouseListener) al);
    }

    public int getItemElegido() {

        int i;

        i = jTableAgenda.getSelectedRow();
        return(i);
    }

    public void setAnchoLista(int ancho) {
    
        jSplitPane1.setDividerLocation(ancho);
        dividerlocation = ancho;
    }


    public void setFontTablaAgenda(Font f) {
        this.jTableAgenda.setFont(f);
    }

    public void setModelListaConsultas(DefaultTableModel dftm) {
        jTableAgenda.setModel(dftm);
    }

    public void setPacienteElegido(int pacienteElegido) {

        if(pacienteElegido < jTableAgenda.getRowCount()) {
            jTableAgenda .setRowSelectionInterval(pacienteElegido, pacienteElegido);
        }
    }

    public void setPanelUtil(JPanel unPanel) {
        scrollUtil.setViewportView(unPanel);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        botonSalir = new javax.swing.JButton();
        buscar = new com.kcreativa.pitosycornetas.KTextBox();
        scrollActividades = new javax.swing.JScrollPane();
        jTableAgenda = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        scrollUtil = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Consultorio");
        setResizable(false);

        jSplitPane1.setDividerLocation(250);
        jSplitPane1.setLastDividerLocation(300);
        jSplitPane1.setOneTouchExpandable(true);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jToolBar1.setBackground(new java.awt.Color(153, 153, 153));
        jToolBar1.setRollover(true);
        jToolBar1.setToolTipText("barra de tareas");
        jToolBar1.setDoubleBuffered(true);

        botonSalir.setText("Salir");
        botonSalir.setFocusable(false);
        botonSalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonSalir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(botonSalir);

        buscar.setEditando(true);
        jToolBar1.add(buscar);

        jPanel1.add(jToolBar1, java.awt.BorderLayout.PAGE_START);

        jTableAgenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scrollActividades.setViewportView(jTableAgenda);

        jPanel1.add(scrollActividades, java.awt.BorderLayout.CENTER);

        jPanel2.setMinimumSize(new java.awt.Dimension(181, 120));
        jPanel2.setPreferredSize(new java.awt.Dimension(349, 67));
        jPanel1.add(jPanel2, java.awt.BorderLayout.PAGE_END);

        jSplitPane1.setLeftComponent(jPanel1);
        jSplitPane1.setRightComponent(scrollUtil);

        getContentPane().add(jSplitPane1, java.awt.BorderLayout.CENTER);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-697)/2, (screenSize.height-560)/2, 697, 560);
    }// </editor-fold>//GEN-END:initComponents


    public void AgregarCambioBuscarListener(KeyListener ke) {

        buscar.addKeyListener(ke);
    }

    public void doMaximize() {

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-1024)/2, (screenSize.height-768)/2, 1024, 768);
    }

    public void setAnchoColumna(int idx, int ancho) {

        jTableAgenda.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        TableColumn col = jTableAgenda.getColumnModel().getColumn(idx);
        col.setPreferredWidth(ancho);
    }

    public void colapsarListaEspera() {
       dividerlocation = this.jSplitPane1.getDividerLocation();
       this.jSplitPane1.setDividerLocation(0);
    }

    public void expandirListaEspera() {
       //dividerlocation = this.jSplitPane1.getDividerLocation();
       this.jSplitPane1.setDividerLocation(dividerlocation);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonSalir;
    private com.kcreativa.pitosycornetas.KTextBox buscar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTable jTableAgenda;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JScrollPane scrollActividades;
    private javax.swing.JScrollPane scrollUtil;
    // End of variables declaration//GEN-END:variables

}
