/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * UIBuscarEstudios.java
 *
 * Created on 09/06/2009, 12:06:37 AM
 */

package talitakumi.laboratorio.ui;

import java.awt.event.ActionListener;
import java.awt.event.FocusListener;
import java.util.Date;
import javax.swing.table.DefaultTableModel;
import talitakumi.framework.DataParameter;


/**
 *
 * @author eduardo
 */
public class UIBuscarEstudios extends javax.swing.JDialog {

    /** Creates new form UIBuscarEstudios */
    public UIBuscarEstudios(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public Integer getCedula() {

        Integer ced = 0;
        try {
            ced = Integer.parseInt(documento.getText());
        } catch(Exception ex) {
            // No dar bola ante este error, es porque no se puso cedula ya que se apreto el botón buscar
        }
        return(ced);
    }

    public int getLineaElegida() {

        return(jTable1.getSelectedRow());
    }

    public void setCambiarPersonaListener(FocusListener cambiarPersonaListener) {
        documento.addFocusListener(cambiarPersonaListener);
    }

    public void setCerrarListener(ActionListener cerrarListener) {
        cerrar.addActionListener(cerrarListener);
    }

    public void setImprimirListener(ActionListener imprimirEstudioListener) {
        imprimir.addActionListener(imprimirEstudioListener);
    }

    public void setImprimirTirillaListener(ActionListener imprimirEstudioListener) {
        tirilla.addActionListener(imprimirEstudioListener);
    }

    public void setModeloTabla(DefaultTableModel dftm) {
        jTable1.setModel(dftm);

    }

    public void setPersona(DataParameter dp) {

        nombre.setText((String)dp.get("apellidos") + " " + (String)dp.get("nombres"));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cerrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        documento = new com.kcreativa.pitosycornetas.KTextBox();
        nombre = new javax.swing.JLabel();
        imprimir = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        fdesde = new org.jdesktop.swingx.JXDatePicker();
        jLabel3 = new javax.swing.JLabel();
        fhasta = new org.jdesktop.swingx.JXDatePicker();
        buscar = new javax.swing.JButton();
        tirilla = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Buscar estudios");
        setResizable(false);

        cerrar.setText("Cerrar");

        jLabel1.setText("PACIENTE");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Fecha", "Actividad"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        documento.setEditando(true);

        imprimir.setText("Imprimir");

        jLabel2.setText("FECHA DESDE");

        jLabel3.setText("FECHA HASTA");

        buscar.setText("Buscar");
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });

        tirilla.setText("Emitir tirilla");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(imprimir)
                .addGap(101, 101, 101)
                .addComponent(tirilla)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 141, Short.MAX_VALUE)
                .addComponent(cerrar)
                .addGap(44, 44, 44))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 559, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fdesde, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fhasta, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                        .addComponent(buscar))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(documento, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(documento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fdesde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fhasta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(imprimir)
                    .addComponent(cerrar)
                    .addComponent(tirilla))
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(593, 447));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscar;
    private javax.swing.JButton cerrar;
    private com.kcreativa.pitosycornetas.KTextBox documento;
    private org.jdesktop.swingx.JXDatePicker fdesde;
    private org.jdesktop.swingx.JXDatePicker fhasta;
    private javax.swing.JButton imprimir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel nombre;
    private javax.swing.JButton tirilla;
    // End of variables declaration//GEN-END:variables

    public Date getFechaDesde() {

        return(fdesde.getDate());
    }

    public Date getFechaHasta() {

        return(fhasta.getDate());
    }

    public void setBuscarListener(ActionListener al) {

        buscar.addActionListener(al);
    }

    public void setFdesdeListener(ActionListener al) {
        fdesde.addActionListener(al);
    }

    public void setFhastaListener(ActionListener al) {
        fhasta.addActionListener(al);
    }

    public void setFechas() {
        fdesde.setDate(new Date());
        fhasta.setDate(new Date());
    }

}
