/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * UIEstudios.java
 *
 * Created on 15-feb-2009, 3:20:37
 */

package talitakumi.laboratorio.ui;

import java.util.Date;
import javax.swing.DefaultCellEditor;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import talitakumi.framework.controller.AbstractVisualController.AlmacenarListener;
import com.kcreativa.pitosycornetas.CheckBoxRenderer;
import com.kcreativa.pitosycornetas.ComboBoxRenderer;
import com.kcreativa.pitosycornetas.KTextBoxRenderer;
import java.awt.event.KeyListener;
import java.util.Vector;
import javax.swing.event.CellEditorListener;
import talitakumi.framework.ui.EachRowEditor;
import talitakumi.framework.ui.EachRowRenderer;

/**
 *
 * @author rupertus
 */
public class UIEstudios extends javax.swing.JPanel {

    EachRowEditor rowEditor;
    EachRowRenderer rowRender;

    /** Creates new form UIEstudios */
    public UIEstudios() {
        initComponents();
        rowEditor = new EachRowEditor(tablaestudios);
        rowRender = new EachRowRenderer();
    }

    public void setAlmacenarListener(AlmacenarListener almacenarListener) {
       almacenar.addActionListener(almacenarListener);
    }

    public void setAnchoColumna(int idx, int ancho) {
        tablaestudios.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        TableColumn col = tablaestudios.getColumnModel().getColumn(idx);
        col.setPreferredWidth(ancho);
        
    }

    public void setApellidosPaciente(String apellidos) {
        apellidopaciente.setText(apellidos);
    }

    public void setCedula(int documento) {
        this.cedulapaciente.setText(documento+"");
    }

    public void setEditorCheckBoxCelda(int linea, DefaultCellEditor checkBoxEditor) {

        CheckBoxRenderer checkBoxRenderer = new CheckBoxRenderer();
        rowRender.add(linea, checkBoxRenderer);
        rowEditor.setEditorAt(linea, checkBoxEditor);
        tablaestudios.getColumn("V. HALLADO").setCellRenderer(rowRender);
        tablaestudios.getColumn("V. HALLADO").setCellEditor(rowEditor);
    }

    public void setEditorKTextBoxCelda(int linea, DefaultCellEditor ktextBoxEditor) {

        KTextBoxRenderer ktextBoxRenderer = new KTextBoxRenderer();
        rowRender.add(linea, ktextBoxRenderer);
        rowEditor.setEditorAt(linea, ktextBoxEditor);
        tablaestudios.getColumn("V. HALLADO").setCellRenderer(rowRender);
        tablaestudios.getColumn("V. HALLADO").setCellEditor(rowEditor);
    }

    public void setEditorListCelda(int linea, DefaultCellEditor jlistEditor, Vector opciones) {
        ComboBoxRenderer comboBoxRenderer = new ComboBoxRenderer(opciones);
        rowRender.add(linea, comboBoxRenderer);
        rowEditor.setEditorAt(linea, jlistEditor);
        tablaestudios.getColumn("V. HALLADO").setCellRenderer(rowRender);
        tablaestudios.getColumn("V. HALLADO").setCellEditor(rowEditor);
       
    }

    public void setFechaNacimiento(Date fechanacimiento) {
        this.fechanacimiento.setText(fechanacimiento + "");
    }

    public void setIdEpisodio(Integer id) {
        episodio.setText(id+"");
    }

    public void setModeloTareas(DefaultTableModel dftm) {
        tablaestudios.setModel(dftm);
    }

    public void setNombreEstudio(String descripcion, int fila) {
        tablaestudios.setValueAt(descripcion, 0, fila);
    }

    public void setNombreAnalisis(String descripcion, int fila) {
        tablaestudios.setValueAt(descripcion, 1, fila);
    }

    public void setValorRefMin(String descripcion, int fila) {
        tablaestudios.setValueAt(descripcion, 2, fila);
    }

    public void setValorRefMax(String descripcion, int fila) {
        tablaestudios.setValueAt(descripcion, 3, fila);
    }

    public void setUnidades(String descripcion, int fila) {
        tablaestudios.setValueAt(descripcion, 4, fila);
    }

    public void setComentarios(String descripcion, int fila) {
        tablaestudios.setValueAt(descripcion, 5, fila);
    }

    public void setNombrePaciente(String nombres) {
        nombrepaciente.setText(nombres);
    }

    public void setSexo(char sexo) {
        this.sexo.setText(sexo+"");
    }

    public void setKeyListener(CellEditorListener kl) {

        rowEditor.addCellEditorListener(kl);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nombrepaciente = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        fechanacimiento = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        sexo = new javax.swing.JLabel();
        apellidopaciente = new javax.swing.JLabel();
        cedulapaciente = new javax.swing.JLabel();
        episodio = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tubo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        almacenar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        obs = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaestudios = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(100, 50));
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 63));

        jLabel1.setText("Paciente");

        nombrepaciente.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        nombrepaciente.setText("jLabel2");

        jLabel2.setText("Fecha nacimiento");

        fechanacimiento.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        fechanacimiento.setText("jLabel3");

        jLabel3.setText("Sexo");

        sexo.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        sexo.setText("M");

        apellidopaciente.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        apellidopaciente.setText("jLabel4");

        cedulapaciente.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        cedulapaciente.setText("jLabelCedula");

        episodio.setText("episodio");

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel5.setText("Tubo");
        jLabel5.setOpaque(true);

        tubo.setBackground(new java.awt.Color(246, 241, 241));
        tubo.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        tubo.setForeground(new java.awt.Color(153, 0, 0));
        tubo.setText("jLabel6");
        tubo.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        tubo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tubo.setOpaque(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(fechanacimiento, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nombrepaciente, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(apellidopaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cedulapaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(23, 23, 23)))
                        .addComponent(sexo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                        .addComponent(episodio))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tubo, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombrepaciente)
                    .addComponent(jLabel1)
                    .addComponent(apellidopaciente)
                    .addComponent(cedulapaciente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(fechanacimiento)
                    .addComponent(jLabel3)
                    .addComponent(sexo)
                    .addComponent(episodio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tubo))
                .addContainerGap())
        );

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setPreferredSize(new java.awt.Dimension(577, 40));

        almacenar.setText("Almacenar");

        obs.setColumns(20);
        obs.setRows(5);
        jScrollPane1.setViewportView(obs);

        jLabel4.setText("OBS:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 427, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(almacenar))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(almacenar)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        add(jPanel2, java.awt.BorderLayout.PAGE_END);

        tablaestudios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tablaestudios);

        add(jScrollPane2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton almacenar;
    private javax.swing.JLabel apellidopaciente;
    private javax.swing.JLabel cedulapaciente;
    private javax.swing.JLabel episodio;
    private javax.swing.JLabel fechanacimiento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel nombrepaciente;
    private javax.swing.JTextArea obs;
    private javax.swing.JLabel sexo;
    private javax.swing.JTable tablaestudios;
    private javax.swing.JLabel tubo;
    // End of variables declaration//GEN-END:variables

    public void setMostrarBotonAlmacenar(boolean b) {

        almacenar.setVisible(b);
    }

    public void agreagarObs(String ensuma) {
        obs.setText(ensuma);
    }

    public String getObservaciones() {

        return(obs.getText());
    }

    public void setTubo(int ntubo) {
        this.tubo.setText(ntubo+"");
    }
}
