/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * UIChequeosVarios.java
 *
 * Created on 22-nov-2010, 13:38:51
 */

package ui;

/**
 *
 * @author rupertus
 */
public class UIChequeosVarios extends javax.swing.JDialog {

    private Integer opcion = null;
    /** Creates new form UIChequeosVarios */
    public UIChequeosVarios(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        ingreso = new javax.swing.JToggleButton();
        preventivo = new javax.swing.JToggleButton();
        santander = new javax.swing.JToggleButton();
        altura = new javax.swing.JToggleButton();
        egreso = new javax.swing.JToggleButton();
        reintegro = new javax.swing.JToggleButton();
        junta = new javax.swing.JToggleButton();
        consultamedica = new javax.swing.JToggleButton();
        bse = new javax.swing.JToggleButton();
        ingresochofer = new javax.swing.JToggleButton();
        chequeopersonalizado = new javax.swing.JToggleButton();
        pesoytalla = new javax.swing.JToggleButton();
        pesoytalla1 = new javax.swing.JToggleButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Chequeos varios");
        setAlwaysOnTop(true);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));

        ingreso.setText("Ingreso");
        ingreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresoActionPerformed(evt);
            }
        });

        preventivo.setText("Preventivo");
        preventivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                preventivoActionPerformed(evt);
            }
        });

        santander.setText("Santander");
        santander.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                santanderActionPerformed(evt);
            }
        });

        altura.setText("Altura");
        altura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alturaActionPerformed(evt);
            }
        });

        egreso.setText("Egreso");
        egreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                egresoActionPerformed(evt);
            }
        });

        reintegro.setText("Reintegro");
        reintegro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reintegroActionPerformed(evt);
            }
        });

        junta.setText("Junta Medica");
        junta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                juntaActionPerformed(evt);
            }
        });

        consultamedica.setText("Consulta médica");
        consultamedica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultamedicaActionPerformed(evt);
            }
        });

        bse.setText("Habilitación BSE");
        bse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bseActionPerformed(evt);
            }
        });

        ingresochofer.setText("Ingreso Chofer");
        ingresochofer.setMaximumSize(new java.awt.Dimension(162, 29));
        ingresochofer.setMinimumSize(new java.awt.Dimension(162, 29));
        ingresochofer.setPreferredSize(new java.awt.Dimension(162, 29));
        ingresochofer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresochoferActionPerformed(evt);
            }
        });

        chequeopersonalizado.setText("Chequeo Personalizado");
        chequeopersonalizado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chequeopersonalizadoActionPerformed(evt);
            }
        });

        pesoytalla.setText("Peso y Talla");
        pesoytalla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesoytallaActionPerformed(evt);
            }
        });

        pesoytalla1.setText("Chequeo de armas");
        pesoytalla1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chequeoArmasActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                        .add(org.jdesktop.layout.GroupLayout.LEADING, chequeopersonalizado, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(org.jdesktop.layout.GroupLayout.LEADING, ingresochofer, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(org.jdesktop.layout.GroupLayout.LEADING, egreso, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(org.jdesktop.layout.GroupLayout.LEADING, bse, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(org.jdesktop.layout.GroupLayout.LEADING, junta, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(org.jdesktop.layout.GroupLayout.LEADING, consultamedica, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(org.jdesktop.layout.GroupLayout.LEADING, santander, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(org.jdesktop.layout.GroupLayout.LEADING, reintegro, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(org.jdesktop.layout.GroupLayout.LEADING, preventivo, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(org.jdesktop.layout.GroupLayout.LEADING, ingreso, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(org.jdesktop.layout.GroupLayout.LEADING, altura, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE))
                    .add(pesoytalla, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE)
                    .add(pesoytalla1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(preventivo)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(ingreso)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(altura)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(reintegro)
                .add(3, 3, 3)
                .add(santander)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(consultamedica)
                .add(12, 12, 12)
                .add(junta)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(bse)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(egreso)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(ingresochofer, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(chequeopersonalizado)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(pesoytalla)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(pesoytalla1)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        getContentPane().add(jScrollPane1);

        jButton1.setText("Cerrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-320)/2, (screenSize.height-408)/2, 320, 408);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        opcion = null;
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void preventivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_preventivoActionPerformed
        // TODO add your handling code here:

        opcion = 2;
        this.setVisible(false);

    }//GEN-LAST:event_preventivoActionPerformed

    private void santanderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_santanderActionPerformed
        // TODO add your handling code here:

        opcion = 3;
        this.setVisible(false);

    }//GEN-LAST:event_santanderActionPerformed

    private void alturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alturaActionPerformed
        // TODO add your handling code here:

        opcion = 4;
        this.setVisible(false);

    }//GEN-LAST:event_alturaActionPerformed

    private void egresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_egresoActionPerformed
        // TODO add your handling code here:
        opcion = 5;
        this.setVisible(false);

    }//GEN-LAST:event_egresoActionPerformed

    private void reintegroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reintegroActionPerformed
        // TODO add your handling code here:

        opcion = 6;
        this.setVisible(false);

    }//GEN-LAST:event_reintegroActionPerformed

    private void juntaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_juntaActionPerformed
        // TODO add your handling code here:

        opcion = 7;
        this.setVisible(false);

    }//GEN-LAST:event_juntaActionPerformed

    private void consultamedicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultamedicaActionPerformed
        // TODO add your handling code here:

        opcion = 8;
        this.setVisible(false);

    }//GEN-LAST:event_consultamedicaActionPerformed

    private void bseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bseActionPerformed
        // TODO add your handling code here:

        opcion = 9;
        this.setVisible(false);

    }//GEN-LAST:event_bseActionPerformed

    private void ingresochoferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresochoferActionPerformed
        // TODO add your handling code here:
        opcion = 10;
        this.setVisible(false);

    }//GEN-LAST:event_ingresochoferActionPerformed

    private void chequeopersonalizadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chequeopersonalizadoActionPerformed
        // TODO add your handling code here:
        opcion = 11;
        this.setVisible(false);

    }//GEN-LAST:event_chequeopersonalizadoActionPerformed

    private void ingresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresoActionPerformed
        // TODO add your handling code here:

        opcion = 1;
        this.setVisible(false);
}//GEN-LAST:event_ingresoActionPerformed

    private void pesoytallaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesoytallaActionPerformed
        // TODO add your handling code here:
        opcion = 12;
        this.setVisible(false);
    }//GEN-LAST:event_pesoytallaActionPerformed

    private void chequeoArmasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chequeoArmasActionPerformed
        // TODO add your handling code here:
        opcion = 13;
        this.setVisible(false);
    }//GEN-LAST:event_chequeoArmasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton altura;
    private javax.swing.JToggleButton bse;
    private javax.swing.JToggleButton chequeopersonalizado;
    private javax.swing.JToggleButton consultamedica;
    private javax.swing.JToggleButton egreso;
    private javax.swing.JToggleButton ingreso;
    private javax.swing.JToggleButton ingresochofer;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton junta;
    private javax.swing.JToggleButton pesoytalla;
    private javax.swing.JToggleButton pesoytalla1;
    private javax.swing.JToggleButton preventivo;
    private javax.swing.JToggleButton reintegro;
    private javax.swing.JToggleButton santander;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the opcion
     */
    public Integer getOpcion() {
        return opcion;
    }

    /**
     * @param opcion the opcion to set
     */
    public void setOpcion(Integer opcion) {
        this.opcion = opcion;
    }

}
