/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * UIFactura.java
 *
 * Created on 25-nov-2008, 8:40:03
 */

package ui;

import java.awt.event.ActionListener;
import java.awt.event.FocusListener;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import talitakumi.model.core.Actividades;
import talitakumi.model.core.Clientes;


/**
 *
 * @author rupertus
 */
public class UIFactura extends javax.swing.JDialog {
    private boolean entregar;
    private boolean pendiente = false;

    /** Creates new form UIFactura */
    public UIFactura(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        entregar = true;
        initComponents();

    }

    public Boolean getDebeImprimir() {

        return(this.emitirticket.isSelected());
    }

    public float getDescuentos() {

        return(Float.parseFloat(descuentos.getText()));
    }

    public String getMotivo() {

        return(motivo.getText());
    }

    public int getNumeroFacturaManual() {

        String x = this.facturamanual.getText();
        int n = 0;
        try {
                n = Integer.parseInt(x);
        } catch(Exception e) {
            n = 0;
        }

        return(n);

    }

    public boolean getPaga() {

        return(paga.isSelected());
    }

    public boolean isEntregar() {
        return(entregar);
    }

    public void setCambiarDescuentosListener(FocusListener cambiarDescuentosListener) {
        descuentos.addFocusListener(cambiarDescuentosListener);
    }

    public void setConcepto(String string) {

        //this.concepto.setText(string);
    }

    public void setIva(String f2) {
        this.iva.setText(f2);
    }

    public void setNumero(int numero) {
        //this.numfactura.setText(numero+"");
    }

    public void setImporte(String f1) {

        this.importe.setText(f1);
    }

    public void setTotal(String f3) {
        this.total.setText(f3);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        importe = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        iva = new javax.swing.JLabel();
        total = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        paga = new javax.swing.JCheckBox();
        motivo = new com.kcreativa.pitosycornetas.KTextBox();
        jLabel5 = new javax.swing.JLabel();
        descuentos = new com.kcreativa.pitosycornetas.KTextBox();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        emitirticket = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        facturamanual = new com.kcreativa.pitosycornetas.KTextBox();
        jButton3 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        procedencia = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        actividades = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        rutcomprador = new com.kcreativa.pitosycornetas.KTextBox();
        nombreempresa = new com.kcreativa.pitosycornetas.KTextBox();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setBackground(java.awt.Color.gray);
        setResizable(false);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logomedilab150x94.jpg"))); // NOI18N

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ok24.png"))); // NOI18N
        jButton1.setText("Entregar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        importe.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        importe.setText("0");

        jLabel4.setText("IVA");

        iva.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        iva.setText("0");

        total.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        total.setText("0");

        jLabel7.setText("TOTAL");

        paga.setSelected(true);
        paga.setText("CREDITO");
        paga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pagaActionPerformed(evt);
            }
        });

        motivo.setEditando(true);

        jLabel5.setText("DESCUENTOS");

        descuentos.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        descuentos.setText("0");

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/button_cancel.png"))); // NOI18N
        jButton2.setText("Cancelar");
        jButton2.setDefaultCapable(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel6.setText("Observaciones");

        emitirticket.setSelected(true);
        emitirticket.setText("EMITIR TICKET");
        emitirticket.setEnabled(false);
        emitirticket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emitirticketActionPerformed(evt);
            }
        });

        jLabel8.setText("FACTURA MANUAL");

        facturamanual.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                facturamanualFocusLost(evt);
            }
        });
        facturamanual.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                facturamanualKeyPressed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pendientes.png"))); // NOI18N
        jButton3.setText("Pendiente");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel9.setText("Procedencia");

        procedencia.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel10.setText("CONCEPTO");

        actividades.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel11.setText("RUT COMPRADOR");

        rutcomprador.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                rutcompradorFocusLost(evt);
            }
        });
        rutcomprador.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                rutcompradorKeyPressed(evt);
            }
        });

        nombreempresa.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                nombreempresaFocusLost(evt);
            }
        });
        nombreempresa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nombreempresaKeyPressed(evt);
            }
        });

        jLabel12.setText("NOMBRE EMPRESA");

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel13.setText("IMPORTE");
        jLabel13.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(actividades, 0, 289, Short.MAX_VALUE))
                                    .addComponent(procedencia, 0, 372, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(63, 63, 63)
                                        .addComponent(jLabel4))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(15, 15, 15)
                                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(149, 149, 149)
                                .addComponent(jLabel9))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(paga)
                                .addGap(18, 18, 18)
                                .addComponent(emitirticket))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel11))
                                .addGap(12, 12, 12)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(facturamanual, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rutcomprador, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nombreempresa, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)))
                .addGap(9, 9, 9))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(motivo, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jButton2)
                .addGap(96, 96, 96)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(65, 65, 65))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(importe, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel5))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(descuentos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(iva, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(total, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)))))
                .addContainerGap(200, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(actividades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(procedencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(importe, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(iva)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(descuentos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(total)
                    .addComponent(jLabel7))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(motivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(paga)
                    .addComponent(emitirticket)
                    .addComponent(jLabel8)
                    .addComponent(facturamanual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(nombreempresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(rutcomprador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addGap(15, 15, 15))
        );

        getAccessibleContext().setAccessibleParent(null);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-545)/2, (screenSize.height-513)/2, 545, 513);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void pagaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pagaActionPerformed
        // TODO add your handling code here:

        emitirticket.setSelected(!this.paga.isSelected());
        emitirticket.setEnabled(!this.paga.isSelected());
    }//GEN-LAST:event_pagaActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        entregar = false;
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void emitirticketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emitirticketActionPerformed
        // TODO add your handling code here:
        habilitarBotonCobrar();
    }//GEN-LAST:event_emitirticketActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        pendiente = true;
        this.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void facturamanualKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_facturamanualKeyPressed
        // TODO add your handling code here:
        habilitarBotonCobrar();
    }//GEN-LAST:event_facturamanualKeyPressed

    private void facturamanualFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_facturamanualFocusLost
        // TODO add your handling code here:
        habilitarBotonCobrar();
    }//GEN-LAST:event_facturamanualFocusLost

    private void rutcompradorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_rutcompradorFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_rutcompradorFocusLost

    private void rutcompradorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rutcompradorKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_rutcompradorKeyPressed

    private void nombreempresaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nombreempresaFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreempresaFocusLost

    private void nombreempresaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombreempresaKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreempresaKeyPressed

    private void habilitarBotonCobrar() {


        if(!emitirticket.isSelected() && !paga.isSelected() && facturamanual.getText().length() < 1){
            jButton1.setEnabled(false);
        }
        else
            if(!emitirticket.isSelected() && facturamanual.getText().length() > 0)
                jButton1.setEnabled(true);
            else
                if(emitirticket.isSelected() || paga.isSelected()){
                    jButton1.setEnabled(true);
                    
            }

        if(emitirticket.isSelected() || paga.isSelected())
            facturamanual.setEnabled(false);
        else
            facturamanual.setEnabled(true);

//        if(procedencia == 'particulares')
//            emitirticket.setEnabled(true);

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox actividades;
    private com.kcreativa.pitosycornetas.KTextBox descuentos;
    private javax.swing.JCheckBox emitirticket;
    private com.kcreativa.pitosycornetas.KTextBox facturamanual;
    private javax.swing.JLabel importe;
    private javax.swing.JLabel iva;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private com.kcreativa.pitosycornetas.KTextBox motivo;
    private com.kcreativa.pitosycornetas.KTextBox nombreempresa;
    private javax.swing.JCheckBox paga;
    private javax.swing.JComboBox procedencia;
    private com.kcreativa.pitosycornetas.KTextBox rutcomprador;
    private javax.swing.JLabel total;
    // End of variables declaration//GEN-END:variables

    public void setContadoHabilitado(boolean b) {
        paga.setEnabled(b);
    }

    public void setContado(boolean b) {
        paga.setSelected(!b);
    }

    public void habilitarEmitir(Boolean b) {

        if(b==null)
            b=false;
        jButton1.setEnabled(b);
    }

    public boolean getPendiente() {
        return(pendiente);
    }

    public void setListaProcedencias(List<Clientes> lp) {


        DefaultComboBoxModel dcbm = new DefaultComboBoxModel();

        for(Clientes p : lp) {

            dcbm.addElement(p.getNombre());
        }

        procedencia.setModel(dcbm);
    }

    public int getProcedenciaElegida() {

        return(procedencia.getSelectedIndex());
    }

    public void setActividadActual(int cliente) {
        actividades.setSelectedIndex(cliente);
    }

    public void setProcedenciaActual(int cliente) {
        procedencia.setSelectedIndex(cliente);
    }

    public void setCambiarProcedenciasListener(ActionListener cambiarProcedenciasListener) {

        procedencia.addActionListener(cambiarProcedenciasListener);
    }

    public int getActividadElegida() {
        return(actividades.getSelectedIndex());
    }

    public void setCambiarActividadesListener(ActionListener cambiarActividadesListener) {

        actividades.addActionListener(cambiarActividadesListener);
    }

    public void setListaActividades(List<Actividades> listaactividades) {

        DefaultComboBoxModel dcbm = new DefaultComboBoxModel();

        for(Actividades p : listaactividades) {

            dcbm.addElement(p.getDescripcion());
        }

        actividades.setModel(dcbm);

    }

    public String getRUTComprador() {

        return(rutcomprador.getText());
    }

    public String getNombreEmpresa() {
        return(nombreempresa.getText());
    }

    public void setEmitirTicket(boolean b) {
        emitirticket.setSelected(b);
        emitirticket.setEnabled(b);
    }

    public void setRut(String rut) {
        rutcomprador.setText(rut);
    }

}
