/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * UILibretaRecepcion.java
 *
 * Created on 27-nov-2008, 22:01:43
 */

package talitakumi.utilidades.ui;

import java.awt.event.ActionListener;
import java.awt.event.FocusListener;
import java.util.Date;
import java.util.List;
import java.util.StringTokenizer;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JPanel;
import talitakumi.framework.DataParameter;
import talitakumi.model.core.Clientes;
import talitakumi.model.core.Procedencias;
import view.UIPaciente;


/**
 *
 * @author rupertus
 */
public class UIChequeoExterno1 extends javax.swing.JDialog {
    public Integer getCodigo1;
    private UIPaciente panelpaciente;

    /** Creates new form UILibretaRecepcion */
    public UIChequeoExterno1() {
        initComponents();

        this.setModal(true);
    }

    public String getEdad(){
        return(edad.getText());
    }

    public void setEdad(String edad){
        this.edad.setText(edad);
    }

    public String getApellidos() {

        return((UIPaciente)panelUtil).getApellidos();
    }

    public int getVigencia(){
        return(vigencia.getSelectedIndex());
    }

    public void setVigencia(int vigencia){
        this.vigencia.setSelectedIndex(vigencia);
    }


    public Integer getCedula() {

//        String cedula = ((UIPaciente)panelUtil).getCedula();
//
//        StringTokenizer st = new StringTokenizer(cedula, "-");
//
//        return Integer.parseInt(st.nextToken());

        String cedula = ((UIPaciente)panelUtil).getCedula();
        Integer ced = null;

        if(cedula.contains("-")) {
           StringTokenizer st = new StringTokenizer(cedula, "-");
           ced = Integer.parseInt(st.nextToken());
        } else
               if(cedula.contains(" ")) {
                   StringTokenizer st = new StringTokenizer(cedula, " ");
                   try {
                      ced = Integer.parseInt(st.nextToken());
                   } catch(Exception ex) {
                       ced = -1;
                   }
               } else
                            try {
                                    ced = Integer.parseInt(cedula);
                            } catch(Exception ex) {
                                    ced = 0;
                            }
        return(ced);
    }

    public String getCiudad() {
        return((UIPaciente)panelUtil).getCiudad();
    }

    public int getClienteELegido() {
        return(jcbClientes.getSelectedIndex());
    }

    public int getIndiceCliente() {
        int idx = jcbProcedencia.getSelectedIndex();

        return(idx);
    }

    public String getDomicilio() {
        return((UIPaciente)panelUtil).getDomicilio();
    }

    public Date getFechanacimiento() {
        return((UIPaciente)panelUtil).getFechanacimiento();
    }

    public void setFechanacimiento(String fn) {
        ((UIPaciente)panelUtil).setFechanacimiento(fn);
    }

    public String getMovil() {
        return((UIPaciente)panelUtil).getMovil();
    }

    public String getNombres() {
        return((UIPaciente)panelUtil).getNombres();
    }

    public JPanel getPanelUtil() {

        return(panelUtil);
    }

   
    public int getProcedenciaElegida() {
        return(jcbProcedencia.getSelectedIndex());
    }

    public char getSexo() {
        return((UIPaciente)panelUtil).getSexo();
    }

    public String getTelefono() {
        return((UIPaciente)panelUtil).getTelefono();
    }

    public void setCedulaListener(FocusListener cedulaListener) {

        ((UIPaciente)panelUtil).setCedulaListener(cedulaListener);
    }

    public void setListaProcedencias(List<Procedencias> lp) {

        DefaultComboBoxModel dcbm = new DefaultComboBoxModel();

        for(Procedencias p : lp) {

            dcbm.addElement(p.getDescripcion());
        }

        jcbProcedencia.setModel(dcbm);
    }

    public void setPanelUtil(JPanel uipac) {

      panelUtil = uipac;
      scrollUtil.setViewportView(uipac);
    }

    public void setGuardarListener(ActionListener al) {

        this.guardar.addActionListener(al);
    }

    public void setCancelarListener(ActionListener al) {

        this.cancelar.addActionListener(al);
    }

    public void setPersona(DataParameter dp) {

        ((UIPaciente)panelUtil).setPaciente(dp);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gupoTipoLibreta = new javax.swing.ButtonGroup();
        jPanel4 = new javax.swing.JPanel();
        panelUtil = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        numerolibreta = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jcbProcedencia = new javax.swing.JComboBox();
        jcbClientes = new javax.swing.JComboBox();
        jLabel19 = new javax.swing.JLabel();
        scrollUtil = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        laboratorio = new javax.swing.JCheckBox();
        medico = new javax.swing.JCheckBox();
        odontologo = new javax.swing.JCheckBox();
        foto = new javax.swing.JCheckBox();
        psicologo = new javax.swing.JCheckBox();
        guardar = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();
        vacuna = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        pap = new javax.swing.JFormattedTextField();
        mamo = new javax.swing.JFormattedTextField();
        MAMO = new javax.swing.JLabel();
        nocorrespondelab = new javax.swing.JCheckBox();
        fecha = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        MAMO1 = new javax.swing.JLabel();
        vigencia = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        nocorrespondefoto = new javax.swing.JCheckBox();
        nocorrespondepsico = new javax.swing.JCheckBox();
        nocorrespondeodo = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        edad = new javax.swing.JTextField();
        dictamenapto = new javax.swing.JCheckBox();
        textlabo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Chequeo externo");
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(255, 255, 255));

        panelUtil.setBackground(new java.awt.Color(102, 0, 0));
        panelUtil.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(941, 941, 941)
                .addComponent(panelUtil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(229, 229, 229)
                .addComponent(panelUtil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logomedilab150x94.jpg"))); // NOI18N

        jLabel17.setFont(new java.awt.Font("Lucida Grande", 0, 24));
        jLabel17.setForeground(new java.awt.Color(0, 51, 153));
        jLabel17.setText("CHEQUEO EXTERNO");

        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("NÚMERO");

        numerolibreta.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        numerolibreta.setText("000000");

        jLabel18.setText("Procedencia");

        jcbProcedencia.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Particular" }));

        jcbClientes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Particular" }));

        jLabel19.setText("CLIENTE");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(jLabel17)
                        .addGap(100, 100, 100)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(numerolibreta, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcbClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100)
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcbProcedencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(1157, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(numerolibreta)
                                .addComponent(jLabel2))
                            .addComponent(jLabel17))
                        .addGap(41, 41, 41)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jcbClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19)
                            .addComponent(jLabel18)
                            .addComponent(jcbProcedencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(64, 64, 64))
        );

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));

        laboratorio.setText("LABORATORIO");

        medico.setText("MÉDICO");

        odontologo.setText("ODONTÓLOGO");

        foto.setText("FOTO");

        psicologo.setText("PSICÓLOGO");
        psicologo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                psicologoActionPerformed(evt);
            }
        });

        guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ok24.png"))); // NOI18N
        guardar.setText("Guardar");

        cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/remove.png"))); // NOI18N
        cancelar.setText("Cancelar");

        vacuna.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        try {
            vacuna.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##-##-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel3.setText("V.ATT");

        jLabel4.setText("PAP");

        pap.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        try {
            pap.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##-##-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        mamo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        try {
            mamo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##-##-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        MAMO.setText("MAMO");

        nocorrespondelab.setText("NO CORRESPONDE");
        nocorrespondelab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nocorrespondelabActionPerformed(evt);
            }
        });

        fecha.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        try {
            fecha.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##-##-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel5.setText("FECHA");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "3", "6", "12" }));

        MAMO1.setText("VIGENCIA");

        vigencia.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "3", "6", "12" }));
        vigencia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                vigenciaMouseClicked(evt);
            }
        });

        jLabel6.setText("VIGENCIA:");

        nocorrespondefoto.setText("NO CORRESPONDE");

        nocorrespondepsico.setText("NO CORRESPONDE");

        nocorrespondeodo.setText("NO CORRESPONDE");

        jLabel7.setText("EDAD");

        edad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                edadMouseClicked(evt);
            }
        });

        dictamenapto.setText("DICTAMEN APTO");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(foto)
                                    .addComponent(psicologo))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nocorrespondefoto)
                                    .addComponent(nocorrespondelab)
                                    .addComponent(nocorrespondepsico)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(edad, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(38, 38, 38)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(laboratorio)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(odontologo)
                                        .addGap(2, 2, 2)))
                                .addComponent(nocorrespondeodo)
                                .addGap(22, 22, 22)
                                .addComponent(textlabo, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(medico, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(MAMO)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(pap, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(vacuna, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(dictamenapto)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jLabel6)
                                                .addGap(3, 3, 3)
                                                .addComponent(vigencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(381, 381, 381)
                                        .addComponent(MAMO1)
                                        .addGap(28, 28, 28)
                                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(mamo, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(guardar)
                                .addGap(18, 18, 18)
                                .addComponent(cancelar)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(MAMO1)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(vacuna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6)
                            .addComponent(vigencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(medico))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(dictamenapto)
                            .addComponent(odontologo)
                            .addComponent(nocorrespondeodo))
                        .addGap(1, 1, 1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mamo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MAMO, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(guardar, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                            .addComponent(cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(psicologo)
                            .addComponent(nocorrespondepsico))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(foto)
                            .addComponent(nocorrespondefoto))
                        .addGap(36, 36, 36))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textlabo, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(laboratorio)
                    .addComponent(nocorrespondelab))
                .addContainerGap(94, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel2, 0, 894, Short.MAX_VALUE)
                            .addComponent(scrollUtil, javax.swing.GroupLayout.DEFAULT_SIZE, 894, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(scrollUtil, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-906)/2, (screenSize.height-607)/2, 906, 607);
    }// </editor-fold>//GEN-END:initComponents

    private void psicologoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_psicologoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_psicologoActionPerformed

    private void nocorrespondelabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nocorrespondelabActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nocorrespondelabActionPerformed

    private void edadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_edadMouseClicked
        // TODO add your handling code here:
        String edad = this.edad.getText();
    }//GEN-LAST:event_edadMouseClicked

    private void vigenciaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vigenciaMouseClicked
        // TODO add your handling code here:
        System.out.println("MARCADO VIGENCIA : " +vigencia.getSelectedIndex());
    }//GEN-LAST:event_vigenciaMouseClicked

    public void setListaClientes(List<Clientes> lp) {


        DefaultComboBoxModel dcbm = new DefaultComboBoxModel();

        for(Clientes p : lp) {

            dcbm.addElement(p.getNombre());
        }

        jcbClientes.setModel(dcbm);
    }

    /**
    * @param args the command line arguments
    */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel MAMO;
    private javax.swing.JLabel MAMO1;
    private javax.swing.JButton cancelar;
    private javax.swing.JCheckBox dictamenapto;
    private javax.swing.JTextField edad;
    private javax.swing.JFormattedTextField fecha;
    private javax.swing.JCheckBox foto;
    private javax.swing.JButton guardar;
    private javax.swing.ButtonGroup gupoTipoLibreta;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JComboBox jcbClientes;
    private javax.swing.JComboBox jcbProcedencia;
    private javax.swing.JCheckBox laboratorio;
    private javax.swing.JFormattedTextField mamo;
    private javax.swing.JCheckBox medico;
    private javax.swing.JCheckBox nocorrespondefoto;
    private javax.swing.JCheckBox nocorrespondelab;
    private javax.swing.JCheckBox nocorrespondeodo;
    private javax.swing.JCheckBox nocorrespondepsico;
    private javax.swing.JLabel numerolibreta;
    private javax.swing.JCheckBox odontologo;
    private javax.swing.JPanel panelUtil;
    private javax.swing.JFormattedTextField pap;
    private javax.swing.JCheckBox psicologo;
    private javax.swing.JScrollPane scrollUtil;
    private javax.swing.JTextField textlabo;
    private javax.swing.JFormattedTextField vacuna;
    private javax.swing.JComboBox vigencia;
    // End of variables declaration//GEN-END:variables

    public void empezarEdicion() {

    }

    public int getMedico() {
        
        int x;
        
        if(medico.isSelected())
            x = 1;
        else
            x = -1;
        return(x);
    }

    public int getOdontologo() {
        
        int x;
        
        if(odontologo.isSelected())
            x = 1;
        else
            x = -1;
        return(x);
    }
    
    public int getLaboratorio() {
        
        int x;
        
        if(laboratorio.isSelected())
            x = 1;
        else
            x = -1;
        return(x);
    }

    public String getFoto() {
        
        String x;
        
        if(foto.isSelected())
            x = "S";
        else
            x = "N";
        return(x);
    }
    
    public int getPsico() {
        
        int x;
        
        if(psicologo.isSelected())
            x = 1;
        else
            x = -1;
        return(x);
    }

    public String getVacuna() {
        return(vacuna.getText());
    }
    
    public String getPAP() {
        return(pap.getText());
    }
    
    public String getMamo() {
        return(mamo.getText());
    }

    public boolean getNoCorrespondeLaboratorio() {
        
        return(nocorrespondelab.isSelected());
    }

    public boolean getNoCorrespondeOdontologo() {

        return(nocorrespondeodo.isSelected());
    }

    public boolean getNoCorrespondeFoto() {

        return(nocorrespondefoto.isSelected());
    }

    public boolean getNoCorrespondePsicologo() {

        return(nocorrespondepsico.isSelected());
    }

    public String getFecha() {
        return(fecha.getText());
    }
    
    public char getDictamenApto(){

        char x;
        
        if(dictamenapto.isSelected())
            x = 'S';
        else
            x = 'N';
        return(x);
        
    }

    public String getTextlabo(){
        return(textlabo.getText());

    }

    public void setTextLabo(String text){
        textlabo.setText(text);
    }

    public void getHabilitarPapYMamo(char sexo){

        if(sexo == 'M'){ // || getSexo()=='M'
            pap.setEnabled(false);
            mamo.setEnabled(false);
        }
        else {
            pap.setEnabled(true);
            mamo.setEnabled(true);
        }
    }

}
