/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * UIConsultorio.java
 *
 * Created on 16-nov-2008, 11:15:37
 */

package talitakumi.utilidades.ui;

import java.awt.event.ActionListener;
import java.awt.event.MouseListener;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author rupertus
 */
public class UIUtilidades extends javax.swing.JFrame {


    /** Creates new form UIConsultorio */
    public UIUtilidades() {
        initComponents();

        jToolBar1.setVisible(true);
    }

    public int getOpcion() {
        return tablamenu.getSelectedRow();
    }

    public void resetVista() {

        jSplitPane1.setDividerLocation(300);
        scrollUtil.getVerticalScrollBar().setValue(0);
        
    }

    public void salirListener(ActionListener al) {

        botonSalir.addActionListener(al);
    }

    public void crearItemListener(MouseListener al) {

        tablamenu.addMouseListener((MouseListener) al);
    }

    public int getItemElegido() {

        int i;

        i = tablamenu.getSelectedRow();
        return(i);
    }

    public void setAnchoLista(int ancho) {
    
        jSplitPane1.setDividerLocation(ancho);
    }

    public void setModeloTareas(DefaultTableModel dftm) {
        tablamenu.setModel(dftm);
        tablamenu.setRowHeight(48);
    }

    public void setPacienteElegido(int pacienteElegido) {

        if(pacienteElegido < tablamenu.getRowCount())
            tablamenu.setRowSelectionInterval(pacienteElegido, pacienteElegido);
    }

    public void setPanelUtil(JPanel unPanel) {
        scrollUtil.setViewportView(unPanel);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        botonSalir = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablamenu = new com.kcreativa.pitosycornetas.TableIcon();
        scrollUtil = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Administracion");
        setUndecorated(true);

        jSplitPane1.setDividerLocation(200);
        jSplitPane1.setOneTouchExpandable(true);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jToolBar1.setBackground(new java.awt.Color(153, 153, 153));
        jToolBar1.setRollover(true);
        jToolBar1.setToolTipText("barra de tareas");
        jToolBar1.setDoubleBuffered(true);

        botonSalir.setText("Salir");
        botonSalir.setFocusable(false);
        botonSalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonSalir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(botonSalir);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Todos" }));
        jToolBar1.add(jComboBox1);

        jPanel1.add(jToolBar1, java.awt.BorderLayout.PAGE_START);

        tablamenu.setGridColor(new java.awt.Color(204, 204, 204));
        jScrollPane1.setViewportView(tablamenu);

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jSplitPane1.setLeftComponent(jPanel1);
        jSplitPane1.setRightComponent(scrollUtil);

        getContentPane().add(jSplitPane1, java.awt.BorderLayout.CENTER);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-1000)/2, (screenSize.height-700)/2, 1000, 700);
    }// </editor-fold>//GEN-END:initComponents


    public void doMaximize() {

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-1024)/2, (screenSize.height-768)/2, 1024, 768);
    }

    public void setAnchoColumna(int idx, int ancho) {

        tablamenu.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        TableColumn col = tablamenu.getColumnModel().getColumn(idx);
        col.setPreferredWidth(ancho);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonSalir;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JScrollPane scrollUtil;
    private com.kcreativa.pitosycornetas.TableIcon tablamenu;
    // End of variables declaration//GEN-END:variables

}
